CREATE TABLE EAI.APLICACION_CENTRAL_HIST
( 
	ANIO_FISCAL VARCHAR2(B, 4),
	DOCUMENTO VARCHAR2(B, 10),
	FECHA DATE,
	VTA_REFERENCIA VARCHAR2(B, 20),
	DEV_REFERENCIA VARCHAR2(B, 20),
	IMPORTE_ASIGNADO NUMBER(15, 2),
	CUSTOMER VARCHAR2(B, 10),
	SAP_VTA_IMPORTE NUMBER(15, 2),
	SAP_DEV_IMPORTE NUMBER(15, 2),
	SAP_VTA_REFERENCIA VARCHAR2(B, 20),
	SAP_DEV_REFERENCIA VARCHAR2(B, 20),
	V3_VTA_IMPORTE NUMBER(15, 2),
	V3_DEV_IMPORTE NUMBER(15, 2),
	V3_VTA_REFERENCIA VARCHAR2(B, 20),
	V3_DEV_REFERENCIA VARCHAR2(B, 20),
	PAGO_INTEGRATION_ID VARCHAR2(B, 30),
	FECHA_PROCESO DATE,
	OBSERVACIONES VARCHAR2(B, 300),
	DEBIT_NOTE VARCHAR2(B, 20),
	ACCNT_ID VARCHAR2(B, 30),
	CLIENTE_V3_VTA VARCHAR2(B, 30),
	CLIENTE_V3_DEV VARCHAR2(B, 30),
	INVC_NUM VARCHAR2(B, 30),
	RFC_VTA VARCHAR2(B, 15),
	RFC_DEV VARCHAR2(B, 15),
	DEBIT_NOTE_WA VARCHAR2(B, 30)
)
/
CREATE TABLE EAI.AR_ESCALACION
( 
	FECHA DATE,
	CREADO_POR VARCHAR2(B, 30),
	PROBLEMA VARCHAR2(B, 255),
	INTERFAZ VARCHAR2(B, 30),
	INCIDENTE VARCHAR2(B, 30),
	SOLUCION VARCHAR2(B, 255),
	REFERENCIA_RCA VARCHAR2(B, 30),
	FECHA_CIERRE DATE,
	ESTADO_TICKET VARCHAR2(B, 10),
	RESPONSABLE VARCHAR2(B, 30),
	REGISTRO VARCHAR2(B, 30),
	FECHA_REGISTRO DATE DEFAULT SYSDATE
)
/
CREATE TABLE EAI.AR_OBELIT_TICKET
( 
	FOLIO_INTERNO NUMBER(6, 0),
	SERVICIO VARCHAR2(B, 10),
	REFERENCIA VARCHAR2(B, 30),
	FECHA DATE,
	CREADO_POR VARCHAR2(B, 30),
	PROBLEMA VARCHAR2(B, 255),
	INTERFAZ VARCHAR2(B, 30),
	INCIDENTE VARCHAR2(B, 30),
	CLASIFICACION VARCHAR2(B, 30),
	PRIORIDAD VARCHAR2(B, 5),
	SOLUCION VARCHAR2(B, 255),
	REFERENCIA_RCA VARCHAR2(B, 30),
	TRANSACCIONES NUMBER(6, 0),
	FECHA_CIERRE DATE,
	ESTADO_TICKET VARCHAR2(B, 10),
	RESPONSABLE VARCHAR2(B, 30),
	REGISTRADO_POR VARCHAR2(B, 30),
	FECHA_REGISTRO DATE DEFAULT SYSDATE
)
/
CREATE TABLE EAI.AR_TICKETS
( 
	TICKET VARCHAR2(B, 30),
	ESTATUS VARCHAR2(B, 30),
	IMPACTO VARCHAR2(B, 30),
	PRIORIDAD VARCHAR2(B, 5),
	FECHA_CREACION DATE,
	FECHA_CIERRE DATE,
	SERVICIO VARCHAR2(B, 30),
	PROBLEMA VARCHAR2(B, 255),
	CREADO_POR VARCHAR2(B, 30),
	ACCION VARCHAR2(B, 30),
	USUARIO_REPORTE VARCHAR2(B, 60),
	TIPO VARCHAR2(B, 30),
	CATEGORIA VARCHAR2(B, 50),
	AREA_AFECTADA_1 VARCHAR2(B, 30),
	AREA_AFECTADA_2 VARCHAR2(B, 30),
	COMENTARIOS VARCHAR2(B, 255),
	SLA VARCHAR2(B, 10),
	RESOLUCIONES NUMBER(6, 0),
	MOVIMIENTOS NUMBER(6, 0),
	USUARIO_ASIGNADO VARCHAR2(B, 30)
)
/
CREATE TABLE EAI.ASIGNACION
( 
	FECHA VARCHAR2(B, 10),
	NUM_DOC_SAP VARCHAR2(B, 10),
	FOLIO_PAGO VARCHAR2(B, 20),
	FOLIO_FACTURA VARCHAR2(B, 20),
	CLIENTE_V3 VARCHAR2(B, 20),
	INTEGRATION_ID VARCHAR2(B, 35),
	MONTO VARCHAR2(B, 15),
	TIPO_DOC VARCHAR2(B, 15)
)
/
CREATE TABLE EAI.ASIGNACION_HO
( 
	FECHA VARCHAR2(B, 10),
	NUM_DOC_SAP VARCHAR2(B, 10),
	FOLIO_PAGO VARCHAR2(B, 15),
	FOLIO_FACTURA VARCHAR2(B, 15),
	CLIENTE_V3 VARCHAR2(B, 20),
	INTEGRATION_ID VARCHAR2(B, 35),
	MONTO VARCHAR2(B, 15),
	TIPO_DOC VARCHAR2(B, 15),
	PROCESAR VARCHAR2(B, 3)
)
/
CREATE TABLE EAI.ASIGNACION_JCR
( 
	FECHA VARCHAR2(B, 10),
	NUM_DOC_SAP VARCHAR2(B, 10),
	FOLIO_PAGO VARCHAR2(B, 15),
	FOLIO_FACTURA VARCHAR2(B, 15),
	CLIENTE_V3 VARCHAR2(B, 20),
	INTEGRATION_ID VARCHAR2(B, 35),
	MONTO VARCHAR2(B, 15),
	TIPO_DOC VARCHAR2(B, 15)
)
/
CREATE TABLE EAI.ASIGNACION_PASO
( 
	FECHA VARCHAR2(B, 10),
	NUM_DOC_SAP VARCHAR2(B, 10),
	FOLIO_PAGO VARCHAR2(B, 15),
	FOLIO_FACTURA VARCHAR2(B, 15),
	CLIENTE_V3 VARCHAR2(B, 20),
	INTEGRATION_ID VARCHAR2(B, 35),
	MONTO VARCHAR2(B, 15),
	TIPO_DOC VARCHAR2(B, 15)
)
/
CREATE TABLE EAI.ASIGNACION_XX
( 
	FECHA VARCHAR2(B, 10),
	NUM_DOC_SAP VARCHAR2(B, 10),
	FOLIO_PAGO VARCHAR2(B, 15),
	FOLIO_FACTURA VARCHAR2(B, 15),
	CLIENTE_V3 VARCHAR2(B, 20),
	INTEGRATION_ID VARCHAR2(B, 35),
	MONTO VARCHAR2(B, 15),
	TIPO_DOC VARCHAR2(B, 15)
)
/
CREATE TABLE EAI.AT_DISTRIB
( 
	DISTRIB NUMBER NOT NULL,
	ALL_REPS NUMBER,
	ALL_SYNCH_REPS NUMBER,
	V3T3_READY CHAR(B, 1) NOT NULL,
	V3T3_READY_TS DATE,
	T3_AGG_READY CHAR(B, 1) NOT NULL,
	T3_AGG_ERROR CHAR(B, 1) NOT NULL,
	T3_AGG_ERR_DOCS NUMBER,
	T3_AGG_START_TS DATE,
	T3_AGG_END_TS DATE,
	EAI_STAGE NUMBER NOT NULL,
	EAI_READY CHAR(B, 1) NOT NULL,
	EAI_ERROR CHAR(B, 1) NOT NULL,
	EAI_START_TS DATE,
	EAI_END_TS DATE
)
/
CREATE TABLE EAI.AT_REP
( 
	DISTRIB NUMBER NOT NULL,
	LOGIN VARCHAR2(B, 10) NOT NULL,
	V3_LAST_LOGIN_TS DATE,
	T3_LAST_INSERT_TS DATE,
	V3T3_READY CHAR(B, 1) NOT NULL,
	V3T3_READY_TS DATE
)
/
CREATE TABLE EAI.CANCELA_DEBIT_NOTE
( 
	DEBITNOTE VARCHAR2(B, 12) NOT NULL,
	FECHA_PROC_BATMD DATE NOT NULL,
	FECHA_CANCELACION DATE,
	PEDIDO VARCHAR2(B, 20)
)
/
CREATE TABLE EAI.CARGA_MENSUAL_VBRK
( 
	DUMMY VARCHAR2(B, 30),
	DOCUMENT VARCHAR2(B, 30),
	STATUS VARCHAR2(B, 30),
	DOC_TYPE VARCHAR2(B, 30),
	DOC_DATE VARCHAR2(B, 30),
	"VALUE" VARCHAR2(B, 30),
	CREATED_BY VARCHAR2(B, 30),
	TIME VARCHAR2(B, 30),
	CREATED VARCHAR2(B, 30),
	PAYER VARCHAR2(B, 30),
	SOLD_TO_PARTY VARCHAR2(B, 30),
	ASSIGMENT VARCHAR2(B, 30),
	REFERENCE VARCHAR2(B, 30)
)
/
CREATE TABLE EAI.CAT_CITIES
( 
	MUNICIPIO VARCHAR2(B, 50) NOT NULL,
	ESTADO VARCHAR2(B, 30) NOT NULL
)
/
CREATE TABLE EAI.CAT_CREDIT_DAYS
( 
	DAYS NUMBER(38, 0) NOT NULL
)
/
CREATE TABLE EAI.CAT_REGIONES
( 
	REGION VARCHAR2(B, 4),
	DESCRIPCION VARCHAR2(B, 40)
)
/
CREATE TABLE EAI.CC_DATA_ALLOCATION
( 
	PLANT VARCHAR2(B, 30),
	TERRITORY VARCHAR2(B, 30),
	DOCUMENT_DATE VARCHAR2(B, 30),
	DOCUMENT_NUMBER VARCHAR2(B, 30),
	MATERIAL VARCHAR2(B, 30),
	UOM VARCHAR2(B, 30),
	SAP_QTY VARCHAR2(B, 30),
	ACTUAL_QTY VARCHAR2(B, 30),
	UMB VARCHAR2(B, 30),
	UOM_1 VARCHAR2(B, 30),
	UOM_2 VARCHAR2(B, 30)
)
/
CREATE TABLE EAI.CC_DATA_OPENITEM
( 
	PLANT VARCHAR2(B, 30),
	SFDC_CUSTOMER VARCHAR2(B, 30),
	SAP_CUSTOMER VARCHAR2(B, 30),
	HEAD_OFFICE VARCHAR2(B, 30),
	PAYMENT_SOURCE VARCHAR2(B, 30),
	SAP_REFERENCE VARCHAR2(B, 30),
	DOCUMENT_DATE VARCHAR2(B, 30),
	DOCUMENT_TYPE VARCHAR2(B, 30),
	SAP_AMOUNT NUMBER(18, 2),
	SFDC_REFERENCE VARCHAR2(B, 30)
)
/
CREATE TABLE EAI.CC_DATA_PAYMENT
( 
	PLANT VARCHAR2(B, 30),
	TERRITORY VARCHAR2(B, 30),
	STOCK_PARTNER VARCHAR2(B, 30),
	SFCD_CUSTOMER VARCHAR2(B, 30),
	SAP_CUSTOMER VARCHAR2(B, 30),
	CUSTOMER_NAME VARCHAR2(B, 100),
	TAX_ID VARCHAR2(B, 30),
	CUSTOMER_PAYMENT_METHOD VARCHAR2(B, 30),
	CUSTOMER_PAYMENT_TYPE VARCHAR2(B, 30),
	REPORT_DATE VARCHAR2(B, 30),
	DOCUMENT_TYPE VARCHAR2(B, 30),
	VOID VARCHAR2(B, 30),
	INVOICE_DATE VARCHAR2(B, 30),
	SFDC_REFERENCE VARCHAR2(B, 30),
	PAC_REFERENCE VARCHAR2(B, 30),
	DOCUMENT_TAX_ID VARCHAR2(B, 30),
	INVOICE_UUID VARCHAR2(B, 40),
	INVOICE_DUE_DATE VARCHAR2(B, 30),
	INVOICE_AMOUNT NUMBER(15, 2),
	INVOICE_PREVIOUS_BALANCE NUMBER(15, 2),
	PAYMENT_METHOD VARCHAR2(B, 30),
	PAYMENT_DATE VARCHAR2(B, 30),
	PAYMENT_ID VARCHAR2(B, 30),
	ASSIGNMENT_ID VARCHAR2(B, 30),
	PAYMENT_NUMBER NUMBER(4, 0),
	COLLECTION_FOR_CASH NUMBER(15, 2),
	COLLECTION_FOR_CREDIT NUMBER(15, 2),
	CREDITMEMO_RELATED VARCHAR2(B, 30),
	CREDITMEMO VARCHAR2(B, 30),
	CREDITMEMO_ALLOCATED NUMBER(15, 2),
	INVOICE_NEW_BALANCE NUMBER(15, 2),
	INVOICE_PAYMENT_METHOD VARCHAR2(B, 30),
	PAYMENT_FISCAL_ID VARCHAR2(B, 30),
	PAYMENT_RELEASE VARCHAR2(B, 30),
	PAYMENT_FISCAL_UUID VARCHAR2(B, 40)
)
/
CREATE TABLE EAI.CC_DATA_SALE
( 
	PLANT VARCHAR2(B, 30),
	INVOICE_DATE VARCHAR2(B, 30),
	DOCUMENT_TYPE VARCHAR2(B, 30),
	SAP_CUSTOMER VARCHAR2(B, 30),
	SFDC_REFERENCE VARCHAR2(B, 30),
	SAP_ORDER_NUMBER VARCHAR2(B, 30),
	PAC_ORDER_NUMBER VARCHAR2(B, 30),
	SAP_SALES_AMOUNT VARCHAR2(B, 30),
	T3_SALES_AMOUNT VARCHAR2(B, 30),
	PAC_SALES_AMOUNT VARCHAR2(B, 30),
	PAC_FISCAL_UUID VARCHAR2(B, 40),
	TERRITORY VARCHAR2(B, 40)
)
/
CREATE TABLE EAI.CC_DATA_STOCK
( 
	PLANT VARCHAR2(B, 30),
	TERRITORY VARCHAR2(B, 30),
	STOCK_PARTNER VARCHAR2(B, 30),
	PARTNER_NAME VARCHAR2(B, 30),
	MATERIAL VARCHAR2(B, 30),
	UOM VARCHAR2(B, 30),
	SAP_QTY VARCHAR2(B, 30),
	ACTUAL_QTY VARCHAR2(B, 30),
	UMB VARCHAR2(B, 30),
	UOM_1 VARCHAR2(B, 30),
	UOM_2 VARCHAR2(B, 30)
)
/
CREATE TABLE EAI.CC_DATA_UNLOAD
( 
	PLANT VARCHAR2(B, 30),
	TERRITORY VARCHAR2(B, 30),
	UNLOAD_DATE VARCHAR2(B, 30),
	UNLOAD_REF_NUMBER VARCHAR2(B, 30),
	MATERIAL VARCHAR2(B, 30),
	UOM VARCHAR2(B, 30),
	SAP_QTY VARCHAR2(B, 30),
	ACTUAL_QTY VARCHAR2(B, 30),
	UMB VARCHAR2(B, 30),
	UOM_1 VARCHAR2(B, 30),
	UOM_2 VARCHAR2(B, 30)
)
/
CREATE TABLE EAI.CC_USUARIO_TEST
( 
	USUARIO VARCHAR2(B, 30),
	NOMBRE VARCHAR2(B, 50),
	ADMINISTRADOR VARCHAR2(B, 2),
	ROL_OPERATIVO VARCHAR2(B, 2),
	ROL_COBRANZA VARCHAR2(B, 2)
)
/
CREATE TABLE EAI.CC_WA_SAP_GI_DATE
( 
	V3_INVOICE VARCHAR2(B, 16),
	V3_DATE VARCHAR2(B, 8),
	R3_DATE VARCHAR2(B, 8),
	CHANGED DATE
)
/
CREATE TABLE EAI.CFDI_BITACORA
( 
	ROW_ID VARCHAR2(B, 20),
	DOC_NUM VARCHAR2(B, 30),
	NOTA_VENTA_CFDI VARCHAR2(B, 30),
	TTL_INVC_AMT NUMBER(12, 2),
	INVC_DT DATE,
	GOODS_DLVRD_TS DATE,
	X_DATE_INTEGRATED DATE,
	FECHA_TRN DATE,
	FECHA_PROC_BATMD DATE,
	FECHA_LIBERACION DATE,
	FECHA_ENVIO DATE,
	FECHA_TIMBRE DATE,
	FECHA_CFD DATE,
	CTRO VARCHAR2(B, 4),
	TERR VARCHAR2(B, 4),
	STATUS VARCHAR2(B, 15),
	TOTAL_CFD NUMBER(12, 2),
	RFC VARCHAR2(B, 15),
	TIPO_VTA VARCHAR2(B, 4),
	DOCTO_IND NUMBER(1, 0),
	DOCTO_SAT NUMBER(1, 0),
	LP VARCHAR2(B, 2),
	DOCTOS NUMBER(3, 0),
	FECHA_VENTA DATE,
	ITEMS NUMBER(3, 0),
	CREATED_BY VARCHAR2(B, 15),
	VOIDDOC VARCHAR2(B, 2),
	CLIENTE_SAP VARCHAR2(B, 10),
	CREDIT_DAYS NUMBER(4, 0),
	BONIF_SUBT NUMBER(15, 2),
	STATUS_CD VARCHAR2(B, 30),
	NOMBRE_CLIENTE VARCHAR2(B, 100),
	VALOR_SUBT NUMBER(15, 2),
	VALOR_IVA NUMBER(15, 2),
	PRIMER_CATEGORIA NUMBER(18, 0),
	SEGUNDA_CATEGORIA NUMBER(10, 0),
	ENVIO_SUBT NUMBER(14, 2),
	ENVIO_IVA NUMBER(14, 2),
	TTL_PD_AMT NUMBER(12, 2),
	FACTURA_SAP VARCHAR2(B, 10),
	CLTE_FACTURA_SAP VARCHAR2(B, 10),
	SAP_AMOUNT NUMBER(15, 2),
	CREDITO_SUBT NUMBER(15, 2),
	CREDITO_IVA NUMBER(15, 2),
	METODO_PAGO VARCHAR2(B, 4),
	FORMA_PAGO VARCHAR2(B, 4),
	SF_AMOUNT NUMBER(15, 2),
	ORIGEN VARCHAR2(B, 4)
)
/
CREATE TABLE EAI.CFDI_ERRORES_NOTA
( 
	REFERENCIA VARCHAR2(B, 30),
	IMPORTE_ORIGINAL NUMBER(15, 2),
	IMPORTE_ASIGNADO NUMBER(15, 2),
	IMPORTE_PENDIENTE NUMBER(15, 2),
	CTRO VARCHAR2(B, 4),
	FECHA_FACTURA DATE,
	FACTURA VARCHAR2(B, 30),
	CLIENTE_SAP VARCHAR2(B, 10),
	VOIDDOC VARCHAR2(B, 3)
)
/
CREATE TABLE EAI.CFDI_INFORME
( 
	SOCIEDAD VARCHAR2(B, 4),
	FOLIO_INTERNO VARCHAR2(B, 30),
	FECHA DATE,
	CTRO VARCHAR2(B, 4),
	TERR VARCHAR2(B, 4),
	TIPO_DOCTO VARCHAR2(B, 4),
	FACTOR NUMBER(2, 0),
	VALOR_SUBT NUMBER(14, 2),
	VALOR_IVA NUMBER(14, 2),
	VALOR NUMBER(14, 2),
	STATUS VARCHAR2(B, 20),
	FOLIO_FISCAL VARCHAR2(B, 40),
	CIGARRILLOS NUMBER(20, 0),
	MONTO_T3IN NUMBER(14, 2),
	RFC VARCHAR2(B, 20),
	GOODS_DLVRD_TS DATE,
	ID_ENVIO VARCHAR2(B, 25),
	ID_CONFIRMACION VARCHAR2(B, 25),
	ADDENDA VARCHAR2(B, 2),
	LP VARCHAR2(B, 2),
	DOCTOS NUMBER(4, 0),
	NOMBRE_CLIENTE VARCHAR2(B, 100),
	ENVIO_SUBT NUMBER(14, 2),
	ENVIO_IVA NUMBER(14, 2),
	DIFERENCIA NUMBER(5, 2),
	CREDITO_SUBT NUMBER(15, 2),
	CREDITO_IVA NUMBER(15, 2),
	ORIGEN VARCHAR2(B, 4)
)
/
CREATE TABLE EAI.CFDI_NOTAS_CREDITO
( 
	REFERENCIA VARCHAR2(B, 31),
	NOTA_VENTA_CFDI VARCHAR2(B, 30),
	IMPORTE_ORIGINAL NUMBER,
	CTRO VARCHAR2(B, 4),
	FECHA_FACTURA DATE,
	FACTURA VARCHAR2(B, 30),
	CLIENTE_SAP VARCHAR2(B, 10),
	RFC VARCHAR2(C, 30),
	VOIDDOC VARCHAR2(B, 2),
	IMPORTE_PENDIENTE NUMBER(15, 2),
	IMPORTE_ASIGNADO NUMBER(15, 2),
	FECHA_DOCUMENTO DATE
)
/
CREATE TABLE EAI.CFDI_OPEN_ITEMS
( 
	CTRO VARCHAR2(B, 4),
	FECHA_VENTA DATE,
	NOTA_VENTA VARCHAR2(B, 30),
	RFC VARCHAR2(B, 20),
	CLIENTE_SAP VARCHAR2(B, 10),
	IMPORTE_VTA NUMBER(16, 2),
	TIPO_DOCTO VARCHAR2(B, 4),
	SALDO_SAP NUMBER(16, 2),
	IMPORTE NUMBER(16, 2),
	EFECTIVO NUMBER(16, 2),
	AGRUPADO NUMBER(16, 2),
	APLICA_NC NUMBER(16, 2),
	EFECTIVO_UUID NUMBER(16, 2),
	AGRUPADO_UUID NUMBER(16, 2),
	APLICA_NC_UUID NUMBER(16, 2),
	IMPORTE_UUID NUMBER(16, 2),
	IMPORTE_NC NUMBER(16, 2),
	FECHA_APLICACION DATE,
	FOLIO_FISCAL VARCHAR2(B, 40),
	LAST_UPDATED DATE,
	NOTA_VENTA_CFDI VARCHAR2(B, 30),
	IMPORTE_NC_UUID NUMBER(16, 2),
	INCOBRABLE NUMBER(16, 2),
	METODO_PAGO VARCHAR2(B, 3),
	CLTE_FACTURA_SAP VARCHAR2(B, 10),
	PEDIDOSAP VARCHAR2(B, 20),
	FACTURASAP VARCHAR2(B, 20)
)
/
CREATE TABLE EAI.CFDI_UUID_NOTA_CREDITO
( 
	CTRO VARCHAR2(B, 4),
	FECHA_VENTA DATE,
	NOTA_VENTA VARCHAR2(B, 30),
	RFC VARCHAR2(B, 20),
	CLIENTE_SAP VARCHAR2(B, 10),
	IMPORTE_VTA NUMBER(16, 2),
	SALDO_SAP NUMBER(16, 2),
	APLICA_NC NUMBER(4, 0),
	IMPORTE_NC NUMBER(16, 2),
	FECHA_APLICACION DATE,
	FOLIO_FISCAL VARCHAR2(B, 40),
	INCOBRABLE NUMBER(16, 2)
)
/
CREATE TABLE EAI.CFDI_UUID_VENTA
( 
	CTRO VARCHAR2(B, 4),
	FECHA_VENTA DATE,
	NOTA_VENTA VARCHAR2(B, 30),
	RFC VARCHAR2(B, 20),
	CLIENTE_SAP VARCHAR2(B, 10),
	IMPORTE_VTA NUMBER(16, 2),
	SALDO_SAP NUMBER(16, 2),
	IMPORTE NUMBER(16, 2),
	EFECTIVO NUMBER(16, 2),
	AGRUPADO NUMBER(16, 2),
	APLICA_NC NUMBER(16, 2),
	EFECTIVO_UUID NUMBER(16, 2),
	AGRUPADO_UUID NUMBER(16, 2),
	APLICA_NC_UUID NUMBER(16, 2),
	IMPORTE_UUID NUMBER(16, 2),
	INCOBRABLE NUMBER(16, 2),
	METODO_PAGO VARCHAR2(B, 3)
)
/
CREATE TABLE EAI.CIFRAS_COMENTARIOS
( 
	REFERENCIA VARCHAR2(B, 20),
	COMENTARIOS VARCHAR2(B, 200),
	FECHA DATE DEFAULT SYSDATE
)
/
CREATE TABLE EAI.CLIENTE_SIEBEL
( 
	CLIENTE_V3 VARCHAR2(C, 50),
	CLIENTE_SAP VARCHAR2(C, 30),
	DIAS_CDTO NUMBER(22, 7),
	RFC VARCHAR2(C, 30),
	LISTA_IVA VARCHAR2(C, 50),
	LISTA_PRECIO VARCHAR2(C, 50),
	TERRITORIO VARCHAR2(C, 75),
	TIPO_TERRITORIO VARCHAR2(C, 30),
	TERRITORIO_DELIVERY VARCHAR2(C, 75),
	TIPO_TERRITORIO_DELIVERY VARCHAR2(C, 30),
	DIST_COBZA VARCHAR2(B, 3),
	FORMA_PAGO VARCHAR2(B, 20),
	CANAL VARCHAR2(B, 2)
)
/
CREATE TABLE EAI.CLIENTES_ERROR
( 
	CLIENTE VARCHAR2(B, 15) NOT NULL,
	MENSAJE VARCHAR2(B, 500),
	REENVIADO VARCHAR2(B, 1) DEFAULT 'N',
	SAP_NUMBER VARCHAR2(B, 15),
	DISTRIBUIDORA VARCHAR2(B, 10),
	FECHA DATE DEFAULT SYSDATE
)
/
CREATE TABLE EAI.CLIENTES_ERROR_LDR
( 
	SAP_NUMBER VARCHAR2(B, 10),
	CLIENTE VARCHAR2(B, 18),
	DISTRIBUIDORA VARCHAR2(B, 4),
	MENSAJE VARCHAR2(B, 500)
)
/
CREATE TABLE EAI.CLIENTES_ERROR_OLD
( 
	CLIENTE VARCHAR2(B, 15) NOT NULL,
	MENSAJE VARCHAR2(B, 500),
	REENVIADO VARCHAR2(B, 1) DEFAULT 'N',
	SAP_NUMBER VARCHAR2(B, 15),
	DISTRIBUIDORA VARCHAR2(B, 10),
	FECHA DATE DEFAULT SYSDATE
)
/
CREATE TABLE EAI.CONTROL_REPORTE
( 
	REPORTE VARCHAR2(B, 50) NOT NULL,
	INICIO DATE,
	FIN DATE,
	DESCRIPCION VARCHAR2(B, 80),
	FILTRO_DISP VARCHAR2(B, 1)
)
/
CREATE TABLE EAI.CUST_TO_SAP
( 
	CUST_V3 VARCHAR2(B, 20) NOT NULL,
	SHIP_TO_V3 VARCHAR2(B, 20) NOT NULL,
	BILL_TO_V3 VARCHAR2(B, 20) NOT NULL,
	PRIMARY_TO_V3 VARCHAR2(B, 20) NOT NULL,
	CUST_TO_SAP VARCHAR2(B, 15),
	SHIP_TO_SAP VARCHAR2(B, 15),
	BILL_TO_SAP VARCHAR2(B, 15),
	CREATED DATE DEFAULT SYSDATE,
	LAST_UPD DATE DEFAULT SYSDATE
)
/
CREATE TABLE EAI.CUSTOMER_LOG
( 
	CLIENTE_V3 VARCHAR2(B, 30),
	FECHA_REPLICACION DATE,
	FECHA_SYNCR DATE,
	FECHA_PROC_BATMD DATE,
	FECHA_UPDATE_SAP DATE,
	FECHA_INSERT DATE,
	FECHA_UPDATE_ERP DATE
)
/
CREATE TABLE EAI.CUSTOMERS_T3_ERROR_LOG
( 
	CUST_ID VARCHAR2(B, 20) NOT NULL,
	LOG_DATE DATE NOT NULL,
	SYSTEM VARCHAR2(B, 5),
	ERR_DESCRIPTION VARCHAR2(B, 200),
	SAP_NUMBER VARCHAR2(B, 20),
	DISTRIBUTOR VARCHAR2(B, 10),
	CTRO VARCHAR2(B, 4)
)
/
CREATE TABLE EAI.CUSTOMERS_T3_ERROR_LOG_HIST
( 
	HIST_DATE DATE NOT NULL,
	CUST_ID VARCHAR2(B, 20) NOT NULL,
	LOG_DATE DATE NOT NULL,
	SYSTEM VARCHAR2(B, 5),
	ERR_DESCRIPTION VARCHAR2(B, 200),
	SAP_NUMBER VARCHAR2(B, 20),
	DISTRIBUTOR VARCHAR2(B, 10)
)
/
CREATE TABLE EAI.DEBITNOTE
( 
	FECHA NVARCHAR2(10),
	MONTO NVARCHAR2(20),
	DOC_ID NVARCHAR2(100),
	CLIENTE_V3 NVARCHAR2(15),
	INTEGRATION_ID NVARCHAR2(35)
)
/
CREATE TABLE EAI.DEBUG_T3
( 
	FECHA DATE,
	FACTURA VARCHAR2(B, 30),
	PEDIDO VARCHAR2(B, 18),
	CLIENTE_SAP VARCHAR2(B, 10),
	COMENTARIO VARCHAR2(B, 250)
)
/
CREATE TABLE EAI.DELIVERY_LDR
( 
	DUMMYFIELD_1 VARCHAR2(B, 30),
	DELIVERY VARCHAR2(B, 20),
	PICKDATE VARCHAR2(B, 20),
	DELIVERYDATE VARCHAR2(B, 20),
	PURCHASEORDER VARCHAR2(B, 20),
	DELIVERYTYPE VARCHAR2(B, 10),
	STATUS VARCHAR2(B, 10),
	PLANT VARCHAR2(B, 10),
	SHIPPINGPOINT VARCHAR2(B, 10),
	SOLDTOPARTY VARCHAR2(B, 20),
	SLOC VARCHAR2(B, 20),
	SHIPTOPARTY VARCHAR2(B, 30),
	SHIPTOPARTYNAME VARCHAR2(B, 50),
	MATERIAL VARCHAR2(B, 20),
	MATERIALNAME VARCHAR2(B, 50),
	QUANTITY VARCHAR2(B, 20),
	UNITMEASURE VARCHAR2(B, 10),
	DUMMYFIELD_2 VARCHAR2(B, 30),
	SHIPTOPARTYLOC VARCHAR2(B, 40),
	SOCIEDAD VARCHAR2(B, 30)
)
/
CREATE TABLE EAI.EAI_CUSTOMER_NO
( 
	CUSTTYPE VARCHAR2(B, 10) NOT NULL,
	CURRENTNO NUMBER(10, 0) NOT NULL
)
/
CREATE TABLE EAI.ENCUESTAS_CLIENTES_BITACORA
( 
	IDEJECUCION NUMBER(30, 0) NOT NULL,
	FECHA_HORA TIMESTAMP(6) NOT NULL,
	TIEMPO_EJECUCION VARCHAR2(C, 20) NOT NULL,
	ESTATUS NUMBER(1, 0) NOT NULL,
	CARGADOS NUMBER(20, 0),
	DESCARTADOS_INEGI NUMBER(20, 0),
	DESCARTADOS_ERRORES NUMBER(20, 0),
	CARGADAS_VALIDAS NUMBER(20, 0),
	MENSAJE VARCHAR2(C, 500)
)
/
CREATE TABLE EAI.ENCUESTAS_CLIENTES_CARGADAS
( 
	IDENCUESTADO VARCHAR2(C, 200),
	IDENCUESTADOR VARCHAR2(C, 200),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	DIRECCIONIP VARCHAR2(C, 20),
	E_MAIL VARCHAR2(C, 200),
	NOMBRE VARCHAR2(C, 200),
	APELLIDO VARCHAR2(C, 200),
	DATOS_PERSONALIZADOS VARCHAR2(C, 200),
	FUENTE VARCHAR2(C, 200),
	VENDE_CIGARRO VARCHAR2(C, 200),
	VISITADO_BAT VARCHAR2(C, 200),
	CUANTO_VENDE VARCHAR2(C, 200),
	VENTA_SEM_PALLMALL VARCHAR2(C, 200),
	VENTA_SEM_LUCKYSTRIKE VARCHAR2(C, 200),
	VENTA_SEM_SHOTS VARCHAR2(C, 200),
	VENTA_SEM_CAMEL VARCHAR2(C, 200),
	VENTA_SEM_OTRASBAT VARCHAR2(C, 200),
	VENTA_SEM_MARLBORO VARCHAR2(C, 200),
	VENTA_SEM_BENSONHEADGES VARCHAR2(C, 200),
	VENTA_SEM_DELICADOS VARCHAR2(C, 200),
	VENTA_SEM_OTRASPMI VARCHAR2(C, 200),
	VENTA_SEM_OTRASMARCAS VARCHAR2(C, 200),
	COORDENADAS VARCHAR2(C, 200),
	TIENE_EXHIBIDOR VARCHAR2(C, 200),
	TELEFONO VARCHAR2(C, 200),
	SEMANA VARCHAR2(C, 200),
	DIA_VISITA VARCHAR2(C, 200),
	CONSECUTIVO VARCHAR2(C, 200),
	NOMBRE_CONTACTO VARCHAR2(C, 200),
	DATOS_GEN_NOMBRETIENDA VARCHAR2(C, 200),
	DATOS_GEN_CALLEYNUMERO VARCHAR2(C, 200),
	DATOS_GEN_COLONIAYCIUDAD VARCHAR2(C, 200),
	DATOS_GEN_CODIGOPOSTAL VARCHAR2(C, 200),
	DATOS_GEN_ESTADO VARCHAR2(C, 200),
	CLIENTE_POTENCIAL VARCHAR2(C, 200),
	TERRITORIO VARCHAR2(C, 20),
	FECHA_REGISTRO DATE DEFAULT SYSDATE,
	PROCESADO NUMBER(1, 0) DEFAULT 0,
	SUPERVISOR VARCHAR2(C, 1) DEFAULT 0
)
/
CREATE TABLE EAI.ENCUESTAS_CLIENTES_ERRORES
( 
	IDERROR NUMBER(30, 0) NOT NULL,
	IDENCUESTA_INVALIDA NUMBER(30, 0) NOT NULL,
	FECHA_REGISTRO DATE,
	MENSAJE_DETALLE VARCHAR2(C, 500),
	CAMPO_ERROR VARCHAR2(C, 30)
)
/
CREATE TABLE EAI.ENCUESTAS_CLIENTES_INEGI
( 
	NOM_ESTAB VARCHAR2(C, 200),
	NOM_PROPIE VARCHAR2(C, 200),
	CLASE_ACT VARCHAR2(C, 200),
	DESC_ACT VARCHAR2(C, 200),
	PERS_OCUP VARCHAR2(C, 200),
	CALLE VARCHAR2(C, 200),
	NUMERO_EXT VARCHAR2(C, 200),
	EDIFICIO VARCHAR2(C, 200),
	NUMERO_INT VARCHAR2(C, 200),
	COLONIA VARCHAR2(C, 200),
	CENTRO_COM VARCHAR2(C, 200),
	NUM_LOCAL VARCHAR2(C, 200),
	COD_POSTAL VARCHAR2(C, 200),
	ENTIDAD VARCHAR2(C, 200),
	MUNICIPIO VARCHAR2(C, 200),
	LOCALIDAD VARCHAR2(C, 200),
	AGEB VARCHAR2(C, 200),
	MANZANA VARCHAR2(C, 200),
	TELEFONO VARCHAR2(C, 200),
	CORREOELEC VARCHAR2(C, 200),
	WWW VARCHAR2(C, 200),
	TIPO_ESTAB VARCHAR2(C, 200),
	LATITUD VARCHAR2(C, 200),
	LONGITUD VARCHAR2(C, 200),
	ID VARCHAR2(C, 200),
	ID_BAT VARCHAR2(C, 200),
	REGION VARCHAR2(C, 200),
	AREA VARCHAR2(C, 200),
	TERRITORIO VARCHAR2(C, 200),
	BLOQUE VARCHAR2(C, 200),
	SEMANA VARCHAR2(C, 200),
	DIA_DE_VISITA VARCHAR2(C, 200),
	CONSECUTIVO VARCHAR2(C, 200),
	CLAVE VARCHAR2(C, 200),
	FUENTE VARCHAR2(C, 200),
	PROSPECTUS_VOLUME_CLASS VARCHAR2(C, 200),
	ENCUESTADO VARCHAR2(C, 200),
	VISITADOS50MTS VARCHAR2(C, 200),
	CEDISBASE VARCHAR2(C, 200),
	NUMERO_SIEBEL VARCHAR2(C, 200)
)
/
CREATE TABLE EAI.ENCUESTAS_CLIENTES_INVALIDAS
( 
	IDENCUESTA_INVALIDA NUMBER(30, 0) NOT NULL,
	TERRITORIO NUMBER(10, 0),
	ANIO_SEMANA NUMBER(6, 0),
	DIA_SEMANA NUMBER(1, 0),
	IDENCUESTADO NUMBER(30, 0),
	IDENCUESTADOR NUMBER(30, 0),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	DIRECCIONIP VARCHAR2(C, 20),
	E_MAIL VARCHAR2(C, 50),
	NOMBRE VARCHAR2(C, 30),
	APELLIDO VARCHAR2(C, 30),
	DATOS_PERSONALIZADOS VARCHAR2(C, 300),
	FUENTE VARCHAR2(C, 10),
	VENDE_CIGARRO VARCHAR2(C, 50),
	VISITADO_BAT VARCHAR2(C, 2),
	CUANTO_VENDE NUMBER(15, 0),
	VENTA_SEM_PALLMALL NUMBER(10, 0),
	VENTA_SEM_LUCKYSTRIKE NUMBER(10, 0),
	VENTA_SEM_SHOTS NUMBER(10, 0),
	VENTA_SEM_CAMEL NUMBER(10, 0),
	VENTA_SEM_OTRASBAT NUMBER(10, 0),
	VENTA_SEM_MARLBORO NUMBER(10, 0),
	VENTA_SEM_BENSONHEADGES NUMBER(10, 0),
	VENTA_SEM_DELICADOS NUMBER(10, 0),
	VENTA_SEM_OTRASPMI NUMBER(10, 0),
	VENTA_SEM_OTRASMARCAS NUMBER(10, 0),
	COORDENADAS VARCHAR2(C, 250),
	TIENE_EXHIBIDOR VARCHAR2(C, 10),
	TELEFONO NUMBER(10, 0),
	SEMANA NUMBER(5, 0),
	DIA_VISITA VARCHAR2(C, 10),
	CONSECUTIVO NUMBER(10, 0),
	NOMBRE_CONTACTO VARCHAR2(C, 200),
	DATOS_GEN_NOMBRETIENDA VARCHAR2(C, 100),
	DATOS_GEN_CALLEYNUMERO VARCHAR2(C, 300),
	DATOS_GEN_COLONIAYCIUDAD VARCHAR2(C, 200),
	DATOS_GEN_CODIGOPOSTAL NUMBER(8, 0),
	DATOS_GEN_ESTADO VARCHAR2(C, 40),
	CLIENTE_POTENCIAL VARCHAR2(B, 20),
	FECHA_REGISTRO DATE DEFAULT SYSDATE,
	IDEJECUCION NUMBER(20, 0) NOT NULL
)
/
CREATE TABLE EAI.ENCUESTAS_CLIENTES_RESUMEN
( 
	TERRITORIO VARCHAR2(C, 20),
	IDENCUESTADO VARCHAR2(C, 200),
	IDENCUESTADOR VARCHAR2(C, 200),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	DIRECCIONIP VARCHAR2(C, 20),
	E_MAIL VARCHAR2(C, 200),
	NOMBRE VARCHAR2(C, 200),
	APELLIDO VARCHAR2(C, 200),
	DATOS_PERSONALIZADOS VARCHAR2(C, 200),
	FUENTE VARCHAR2(C, 200),
	VENDE_CIGARRO VARCHAR2(C, 200),
	VISITADO_BAT VARCHAR2(C, 200),
	CUANTO_VENDE VARCHAR2(C, 200),
	VENTA_SEM_PALLMALL VARCHAR2(C, 200),
	VENTA_SEM_LUCKYSTRIKE VARCHAR2(C, 200),
	VENTA_SEM_SHOTS VARCHAR2(C, 200),
	VENTA_SEM_CAMEL VARCHAR2(C, 200),
	VENTA_SEM_OTRASBAT VARCHAR2(C, 200),
	VENTA_SEM_MARLBORO VARCHAR2(C, 200),
	VENTA_SEM_BENSONHEADGES VARCHAR2(C, 200),
	VENTA_SEM_DELICADOS VARCHAR2(C, 200),
	VENTA_SEM_OTRASPMI VARCHAR2(C, 200),
	VENTA_SEM_OTRASMARCAS VARCHAR2(C, 200),
	COORDENADAS VARCHAR2(C, 200),
	TIENE_EXHIBIDOR VARCHAR2(C, 200),
	TELEFONO VARCHAR2(C, 200),
	SEMANA VARCHAR2(C, 200),
	DIA_VISITA VARCHAR2(C, 200),
	CONSECUTIVO VARCHAR2(C, 200),
	NOMBRE_CONTACTO VARCHAR2(C, 200),
	DATOS_GEN_NOMBRETIENDA VARCHAR2(C, 200),
	DATOS_GEN_CALLEYNUMERO VARCHAR2(C, 200),
	DATOS_GEN_COLONIAYCIUDAD VARCHAR2(C, 200),
	DATOS_GEN_CODIGOPOSTAL VARCHAR2(C, 200),
	DATOS_GEN_ESTADO VARCHAR2(C, 200),
	CLIENTE_POTENCIAL VARCHAR2(C, 200),
	VLD_NO_EN_INEGI NUMBER(1, 0),
	VLD_TERRITORIO NUMBER(1, 0),
	VLD_IDENCUESTADO NUMBER(1, 0),
	VLD_IDENCUESTADOR NUMBER(1, 0),
	VLD_FECHA_INICIO NUMBER(1, 0),
	VLD_FECHA_FIN NUMBER(1, 0),
	VLD_DIRECCIONIP NUMBER(1, 0),
	VLD_E_MAIL NUMBER(1, 0),
	VLD_NOMBRE NUMBER(1, 0),
	VLD_APELLIDO NUMBER(1, 0),
	VLD_DATOS_PERSONALIZADOS NUMBER(1, 0),
	VLD_FUENTE NUMBER(1, 0),
	VLD_VENDE_CIGARRO NUMBER(1, 0),
	VLD_VISITADO_BAT NUMBER(1, 0),
	VLD_CUANTO_VENDE NUMBER(1, 0),
	VLD_VENTA_SEM_PALLMALL NUMBER(1, 0),
	VLD_VENTA_SEM_LUCKYSTRIKE NUMBER(1, 0),
	VLD_VENTA_SEM_SHOTS NUMBER(1, 0),
	VLD_VENTA_SEM_CAMEL NUMBER(1, 0),
	VLD_VENTA_SEM_OTRASBAT NUMBER(1, 0),
	VLD_VENTA_SEM_MARLBORO NUMBER(1, 0),
	VLD_VENTA_SEM_BENSONHEADGES NUMBER(1, 0),
	VLD_VENTA_SEM_DELICADOS NUMBER(1, 0),
	VLD_VENTA_SEM_OTRASPMI NUMBER(1, 0),
	VLD_VENTA_SEM_OTRASMARCAS NUMBER(1, 0),
	VLD_COORDENADAS NUMBER(1, 0),
	VLD_TIENE_EXHIBIDOR NUMBER(1, 0),
	VLD_TELEFONO NUMBER(1, 0),
	VLD_SEMANA NUMBER(1, 0),
	VLD_DIA_VISITA NUMBER(1, 0),
	VLD_CONSECUTIVO NUMBER(1, 0),
	VLD_NOMBRE_CONTACTO NUMBER(1, 0),
	VLD_DATOS_GEN_NOMBRETIENDA NUMBER(1, 0),
	VLD_DATOS_GEN_CALLEYNUMERO NUMBER(1, 0),
	VLD_DATOS_GEN_COLONIAYCIUDAD NUMBER(1, 0),
	VLD_DATOS_GEN_CODIGOPOSTAL NUMBER(1, 0),
	VLD_DATOS_GEN_ESTADO NUMBER(1, 0),
	VLD_CLIENTE_POTENCIAL NUMBER(1, 0),
	INEGI_NOM_ESTAB VARCHAR2(C, 200),
	INEGI_CALLE VARCHAR2(C, 200),
	INEGI_NUMERO_EXT VARCHAR2(C, 200),
	INEGI_COLONIA VARCHAR2(C, 200),
	INEGI_COD_POSTAL VARCHAR2(C, 200),
	INEGI_ENTIDAD VARCHAR2(C, 200),
	INEGI_MUNICIPIO VARCHAR2(C, 200),
	INEGI_LOCALIDAD VARCHAR2(C, 200),
	INEGI_TELEFONO VARCHAR2(C, 200),
	INEGI_LATITUD VARCHAR2(C, 200),
	INEGI_LONGITUD VARCHAR2(C, 200),
	INEGI_ID_BAT VARCHAR2(C, 200),
	INEGI_CLAVE VARCHAR2(C, 200),
	SUPERVISOR VARCHAR2(C, 1) DEFAULT 0
)
/
CREATE TABLE EAI.ENCUESTAS_CLIENTES_VALIDAS
( 
	IDENCUESTA NUMBER(30, 0) NOT NULL,
	TERRITORIO NUMBER(10, 0) NOT NULL,
	ANIO_SEMANA NUMBER(6, 0) NOT NULL,
	DIA_SEMANA NUMBER(1, 0) NOT NULL,
	IDENCUESTADO NUMBER(30, 0) NOT NULL,
	IDENCUESTADOR NUMBER(30, 0) NOT NULL,
	FECHA_INICIO DATE NOT NULL,
	FECHA_FIN DATE NOT NULL,
	DIRECCIONIP VARCHAR2(C, 20) NOT NULL,
	E_MAIL VARCHAR2(C, 50),
	NOMBRE VARCHAR2(C, 30),
	APELLIDO VARCHAR2(C, 30),
	DATOS_PERSONALIZADOS VARCHAR2(C, 300),
	FUENTE VARCHAR2(C, 10) NOT NULL,
	VENDE_CIGARRO VARCHAR2(C, 50) NOT NULL,
	VISITADO_BAT VARCHAR2(C, 2),
	CUANTO_VENDE NUMBER(15, 0),
	VENTA_SEM_PALLMALL NUMBER(10, 0),
	VENTA_SEM_LUCKYSTRIKE NUMBER(10, 0),
	VENTA_SEM_SHOTS NUMBER(10, 0),
	VENTA_SEM_CAMEL NUMBER(10, 0),
	VENTA_SEM_OTRASBAT NUMBER(10, 0),
	VENTA_SEM_MARLBORO NUMBER(10, 0),
	VENTA_SEM_BENSONHEADGES NUMBER(10, 0),
	VENTA_SEM_DELICADOS NUMBER(10, 0),
	VENTA_SEM_OTRASPMI NUMBER(10, 0),
	VENTA_SEM_OTRASMARCAS NUMBER(10, 0),
	COORDENADAS VARCHAR2(C, 250),
	TIENE_EXHIBIDOR VARCHAR2(C, 10),
	TELEFONO NUMBER(10, 0),
	SEMANA NUMBER(5, 0) NOT NULL,
	DIA_VISITA VARCHAR2(C, 10) NOT NULL,
	CONSECUTIVO NUMBER(10, 0) NOT NULL,
	NOMBRE_CONTACTO VARCHAR2(C, 200),
	DATOS_GEN_NOMBRETIENDA VARCHAR2(C, 100),
	DATOS_GEN_CALLEYNUMERO VARCHAR2(C, 300),
	DATOS_GEN_COLONIAYCIUDAD VARCHAR2(C, 200),
	DATOS_GEN_CODIGOPOSTAL NUMBER(8, 0),
	DATOS_GEN_ESTADO VARCHAR2(C, 40),
	CLIENTE_POTENCIAL VARCHAR2(B, 20),
	FECHA_REGISTRO DATE DEFAULT SYSDATE,
	ESTATUS NUMBER(2, 0) DEFAULT 0
)
/
CREATE TABLE EAI.ERROR_TABLE
( 
	DISTRIBUTOR NUMBER(4, 0),
	PROCESS VARCHAR2(B, 50),
	DOC_NUM VARCHAR2(B, 20),
	ERR_DATE DATE,
	MESSAGE VARCHAR2(B, 500),
	CTRO VARCHAR2(B, 4)
)
/
CREATE TABLE EAI.ERROR_TRANSLATE_V3
( 
	ERROR VARCHAR2(B, 200) NOT NULL,
	DESCRIPTION VARCHAR2(B, 100) NOT NULL
)
/
CREATE TABLE EAI.FC__REP_DISTRIBUTOR
( 
	REP_ID VARCHAR2(B, 20),
	DISTRIBUTOR VARCHAR2(B, 3),
	START_DATE DATE DEFAULT TO_DATE('24/11/2003 06:00:00','dd/mm/yyyy hh24:mi:ss') NOT NULL,
	END_DATE DATE DEFAULT TO_DATE('31/12/4000 23:59:59','dd/mm/yyyy hh24:mi:ss') NOT NULL,
	CREATED VARCHAR2(B, 32) DEFAULT TO_CHAR(SYSTIMESTAMP,'DDMMYYYYHH24MISSFFFF') NOT NULL,
	CTRO VARCHAR2(B, 4),
	UBICACION VARCHAR2(B, 4)
)
/
CREATE TABLE EAI.FC__TIME_WINDOW
( 
	START_DATE VARCHAR2(B, 19) NOT NULL,
	END_DATE VARCHAR2(B, 19) NOT NULL,
	MANDANT VARCHAR2(B, 3) NOT NULL
)
/
CREATE TABLE EAI.HIST_EVIDENCIAS_ENTREGA
( 
	ITEMINTERNALID VARCHAR2(B, 100),
	FECHA VARCHAR2(B, 100),
	TIENDA VARCHAR2(B, 100),
	FOLIO_RECEPCION VARCHAR2(B, 100),
	VOLUMEN_TICKET NUMBER(8, 0),
	FOLIO_INTERNO VARCHAR2(B, 100),
	VOLUMEN_NOTA NUMBER(8, 0),
	COINCIDEVOLUMEN VARCHAR2(B, 100),
	INSERT_TS DATE,
	UPDATE_TS DATE
)
/
CREATE TABLE EAI.IFC_FOLIOS_CONFIG
( 
	ROW_ID NUMBER NOT NULL,
	SERVER VARCHAR2(B, 100),
	USERNAME VARCHAR2(B, 50),
	PWD VARCHAR2(B, 50),
	PATH_BATCH VARCHAR2(B, 300),
	CLIENTE VARCHAR2(B, 100),
	RFC VARCHAR2(B, 100),
	PATH_UNIX VARCHAR2(B, 300),
	PATH_LOCAL VARCHAR2(B, 300),
	PATH_TO_MOV VARCHAR2(B, 300),
	TAG_PREVIO VARCHAR2(B, 300),
	TAG_A_MODIFICAR VARCHAR2(B, 300),
	ESTATUS VARCHAR2(B, 20),
	X_VAR1 VARCHAR2(B, 300),
	X_VAR2 VARCHAR2(B, 300),
	X_VAR3 VARCHAR2(B, 300),
	X_INT1 NUMBER,
	X_INT2 NUMBER,
	X_FLOAT1 NUMBER(13, 2),
	X_FLOAT2 NUMBER(13, 2),
	X_DATE1 DATE,
	X_DATE2 DATE,
	TAG_A_MODIFICAR_CIERRE VARCHAR2(B, 300),
	PATH_PDF_UNIX VARCHAR2(B, 300),
	PATH_PDF_LOCAL VARCHAR2(B, 300),
	MAIL_TO VARCHAR2(B, 1000),
	MAIL_CC VARCHAR2(B, 1000),
	PATH_PDF_TO_MOVE VARCHAR2(B, 300),
	CREADOPOR VARCHAR2(B, 40),
	CREACION DATE,
	MODIFICADOPOR VARCHAR2(B, 40),
	MODIFICACION DATE
)
/
CREATE TABLE EAI.IFC_FOLIOS_CONFIG_EMAIL
( 
	RFC VARCHAR2(B, 20),
	CLIENTE_V3 VARCHAR2(B, 100),
	EMAIL VARCHAR2(B, 100),
	TIPO VARCHAR2(B, 3),
	CREADO_POR VARCHAR2(B, 30),
	CREACION DATE,
	MODIFICADO_POR VARCHAR2(B, 30),
	MODIFICACION DATE,
	VAR_1 VARCHAR2(B, 300),
	VAR_2 VARCHAR2(B, 300),
	INT_1 NUMBER(38, 0),
	INT_2 NUMBER(38, 0),
	X_FLOAT1 FLOAT(4),
	X_FLOAT2 FLOAT(4),
	X_DATE1 DATE,
	X_DATE2 DATE
)
/
CREATE TABLE EAI.IFC_FOLIOS_FE
( 
	ROW_ID NUMBER NOT NULL,
	RFC_RECEPTOR VARCHAR2(B, 20),
	SERIE VARCHAR2(B, 20),
	FOLIO VARCHAR2(B, 20),
	PEDIDO VARCHAR2(B, 30),
	ENTRADA VARCHAR2(B, 30),
	FECHA DATE,
	TIPO VARCHAR2(B, 20),
	CREADOPOR VARCHAR2(B, 20),
	CREACION DATE,
	MODIFICADOPOR VARCHAR2(B, 20),
	MODIFICACION DATE,
	VAR_1 VARCHAR2(B, 100),
	VAR_2 VARCHAR2(B, 100),
	INT_1 NUMBER,
	INT_2 NUMBER,
	FLOAT_1 NUMBER(10, 6),
	FLOAT_2 NUMBER(10, 6),
	ESTATUS VARCHAR2(B, 20)
)
/
CREATE TABLE EAI.INCONSISTENCIAS
( 
	INTERFAZ VARCHAR2(B, 30),
	REFERENCIA VARCHAR2(B, 30)
)
/
CREATE TABLE EAI.INVENTARIO_TAO
( 
	MKPF_BLDAT VARCHAR2(B, 30),
	MKPF_BUDAT VARCHAR2(B, 30),
	MKPF_MTSNR VARCHAR2(B, 30),
	MKPF_BKTST VARCHAR2(B, 30),
	MSEG_BWART VARCHAR2(B, 30),
	MSEG_SOBKZ VARCHAR2(B, 30),
	MSEG_WERKS VARCHAR2(B, 30),
	MSEG_LGORT VARCHAR2(B, 30),
	MSEG_GRUND VARCHAR2(B, 30),
	MSEG_LIFNR VARCHAR2(B, 30),
	MSEG_KUNNR VARCHAR2(B, 30),
	MSEG_MATNR VARCHAR2(B, 30),
	MSEG_ERFMG NUMBER(12, 2),
	MSEG_ERFME VARCHAR2(B, 30),
	MKPF_BKTXT VARCHAR2(B, 30),
	MSEG_KUNNR_TAO VARCHAR2(B, 30),
	MSEG_MATNR_TAO VARCHAR2(B, 30)
)
/
CREATE TABLE EAI.LDR_DELPHIC
( 
	SAP_CUSTOMER_CLEAN VARCHAR2(B, 30),
	SKU_CODE VARCHAR2(B, 30),
	WEEK_START VARCHAR2(B, 30),
	SUGGESTED_ORDER_DAILY NUMBER(12, 4)
)
/
CREATE TABLE EAI.LDR_EVIDENCIAS_ENTREGA
( 
	DUMMY_FIELD1 VARCHAR2(B, 100),
	ITEMINTERNALID VARCHAR2(B, 100),
	FECHA VARCHAR2(B, 100),
	TIENDA VARCHAR2(B, 100),
	FOLIO_RECEPCION VARCHAR2(B, 100),
	VOLUMEN_TICKET NUMBER(8, 0),
	FOLIO_INTERNO VARCHAR2(B, 100),
	VOLUMEN_NOTA NUMBER(8, 0),
	COINCIDEVOLUMEN VARCHAR2(B, 100)
)
/
CREATE TABLE EAI.LDR_FLB5N
( 
	SOCIEDAD VARCHAR2(B, 10),
	CUENTA_MAYOR VARCHAR2(B, 30),
	CLIENTE_SAP VARCHAR2(B, 10),
	FECHA_CONTABLE VARCHAR2(B, 10),
	FECHA_DOCUMENTO VARCHAR2(B, 10),
	EJERCICIO_FISCAL VARCHAR2(B, 10),
	REFERENCIA VARCHAR2(B, 30),
	DOCTO_COMPENSACION VARCHAR2(B, 10),
	FECHA_COMPENSACION VARCHAR2(B, 10),
	DOCUMENTO VARCHAR2(B, 10),
	CLASE_DOCTO VARCHAR2(B, 10),
	CLAVE_CONTABLE VARCHAR2(B, 10),
	DC_INDICATOR VARCHAR2(B, 1),
	IMPORTE VARCHAR2(B, 30),
	MONEDA VARCHAR2(B, 10),
	TIPO_CAMBIO VARCHAR2(B, 20),
	TEXTO_CABECERA VARCHAR2(B, 60),
	TEXTO_ADICIONAL VARCHAR2(B, 60),
	INDICADOR_IMPUESTO VARCHAR2(B, 10),
	IMPORTE_RETENIDO VARCHAR2(B, 20),
	REFERENCIA_FACTURA VARCHAR2(B, 20),
	DOCTO_VENTAS VARCHAR2(B, 10),
	FACTURA VARCHAR2(B, 10),
	ASIGNACION VARCHAR2(B, 20),
	CLAVE_REFERENCIA VARCHAR2(B, 20),
	ANULAR_COMPENSACION VARCHAR2(B, 10),
	EJERCICIO_COMPENSACION VARCHAR2(B, 10),
	FECHA_REGISTRO VARCHAR2(B, 10),
	PERIODO VARCHAR2(B, 10),
	DUMMY_FIELD1 VARCHAR2(B, 20),
	DUMMY_FIELD2 VARCHAR2(B, 20),
	DUMMY_FIELD3 VARCHAR2(B, 20),
	MONEDA_DOCUMENTO VARCHAR2(B, 10)
)
/
CREATE TABLE EAI.LDR_MX16_CENTRALIZADO
( 
	STATUS VARCHAR2(B, 20),
	TABLE_ROW VARCHAR2(B, 20),
	SEPARATOR VARCHAR2(B, 10),
	DOCUMENTDATE VARCHAR2(B, 20),
	POSTINGDATE VARCHAR2(B, 20),
	DOCUMENTTYPE VARCHAR2(B, 4),
	COMPANYCODE VARCHAR2(B, 4),
	CURRENCY VARCHAR2(B, 10),
	BILLINGDOCUMENT VARCHAR2(B, 10),
	REFERENCEDOCUMENT VARCHAR2(B, 20),
	DOCUMENTHEADERTEXT VARCHAR2(B, 40),
	CUSTOMER VARCHAR2(B, 20),
	ACCOUNT_GL VARCHAR2(B, 20),
	ITEMTEXT VARCHAR2(B, 40),
	ASSIGNMENT VARCHAR2(B, 20),
	PAYMENT VARCHAR2(B, 20),
	SEPARATOR2 VARCHAR2(B, 10),
	FISCALYEAR VARCHAR2(B, 4),
	INVOICEACCDOC VARCHAR2(B, 10),
	INVOICEAMOUNT VARCHAR2(B, 20),
	POSTINGCODE VARCHAR2(B, 4),
	SD_DOCUMENT VARCHAR2(B, 10),
	CLEARINGDOCUMENT VARCHAR2(B, 10),
	RESIDUALDOCUMENT VARCHAR2(B, 10),
	MESSAGETEXT VARCHAR2(B, 100),
	MSGTYPE VARCHAR2(B, 100),
	MSGCLAS VARCHAR2(B, 100),
	MSGNUMBER VARCHAR2(B, 100)
)
/
CREATE TABLE EAI.LDR_MX16_NC_CENTRALIZADO
( 
	STATUS VARCHAR2(B, 20),
	TABLE_ROW VARCHAR2(B, 20),
	SEPARATOR VARCHAR2(B, 10),
	DOCUMENTDATE VARCHAR2(B, 20),
	POSTINGDATE VARCHAR2(B, 20),
	COMPANYCODE VARCHAR2(B, 4),
	CURRENCY VARCHAR2(B, 10),
	BILLINGDOCUMENT VARCHAR2(B, 10),
	REFERENCEDOCUMENT VARCHAR2(B, 20),
	NC_BILLINGDOCUMENT VARCHAR2(B, 10),
	NC_REFERENCEDOCUMENT VARCHAR2(B, 20),
	DOCUMENTHEADERTEXT VARCHAR2(B, 40),
	CUSTOMER VARCHAR2(B, 20),
	TEXT_REFERENCE_1 VARCHAR2(B, 60),
	TEXT_REFERENCE_2 VARCHAR2(B, 60),
	PAYMENT VARCHAR2(B, 20),
	DOCUMENTTYPE VARCHAR2(B, 4),
	SEPARATOR2 VARCHAR2(B, 10),
	FISCALYEAR VARCHAR2(B, 4),
	INVOICEACCDOC VARCHAR2(B, 10),
	INVOICEAMOUNT VARCHAR2(B, 20),
	FISCALYEAR2 VARCHAR2(B, 4),
	CN_ACCDOC VARCHAR2(B, 10),
	CREDIT_AMOUNT VARCHAR2(B, 20),
	POSTINGCODE VARCHAR2(B, 4),
	SD_DOCUMENT VARCHAR2(B, 10),
	CLEARINGDOCUMENT VARCHAR2(B, 10),
	RESIDUALDOCUMENT VARCHAR2(B, 10),
	NC_RESIDUALDOCUMENT VARCHAR2(B, 10),
	MESSAGETEXT VARCHAR2(B, 100),
	MSGTYPE VARCHAR2(B, 100),
	MSGCLAS VARCHAR2(B, 100),
	MSGNUMBER VARCHAR2(B, 100)
)
/
CREATE TABLE EAI.LDR_NGP_DATA
( 
	INSTALL_ID VARCHAR2(B, 5),
	TICKET VARCHAR2(B, 20),
	PURCHASE_DATE VARCHAR2(B, 20),
	PURCHASE_TIME VARCHAR2(B, 10),
	PURCHASE_TYPE VARCHAR2(B, 10),
	PRICE_LIST VARCHAR2(B, 2),
	CUSTOMER_ID VARCHAR2(B, 30),
	CUSTOMER_NIF VARCHAR2(B, 20),
	CUSTOMER_NAME VARCHAR2(B, 100),
	CUSTOMER_ADDRESS VARCHAR2(B, 100),
	CUSTOMER_DISTRICT VARCHAR2(B, 60),
	CUSTOMER_CITY VARCHAR2(B, 60),
	CUSTOMER_STATE VARCHAR2(B, 60),
	CUSTOMER_COUNTRY VARCHAR2(B, 30),
	CUSTOMER_ZIPCODE VARCHAR2(B, 10),
	PAYMENT_METHOD VARCHAR2(B, 20),
	MATERIAL VARCHAR2(B, 10),
	UNITMEASURE VARCHAR2(B, 6),
	QUANTITY NUMBER(10, 2),
	EXTND_PRICE NUMBER(15, 4),
	EXTND_TAX NUMBER(15, 4),
	EXTND_DISCOUNT NUMBER(15, 4),
	DISTRIBUTION_FEE NUMBER(15, 4),
	CUSTOMER_FIRST_NAME VARCHAR2(B, 60),
	CUSTOMER_LAST_NAME VARCHAR2(B, 60),
	SHIPMENT_DATE VARCHAR2(B, 10),
	ITEM_CATEGORY VARCHAR2(B, 10),
	USAGE_INDICATOR VARCHAR2(B, 10),
	ITEM_LINE_NUMBER VARCHAR2(B, 10)
)
/
CREATE TABLE EAI.LDR_SALES_METRIC
( 
	OBJECT_NAME VARCHAR2(B, 50),
	ID VARCHAR2(B, 50),
	RETAILER__C VARCHAR2(B, 50),
	PRODUCT__C VARCHAR2(B, 50),
	QUANTITY__C VARCHAR2(B, 50),
	CREATEDDATE VARCHAR2(B, 50)
)
/
CREATE TABLE EAI.LDR_SHAREPOINT
( 
	DUMMY1 VARCHAR2(B, 100),
	ITEMINTERNALID VARCHAR2(B, 100),
	FECHA VARCHAR2(B, 100),
	TIENDA VARCHAR2(B, 100),
	FOLIORECEPCION VARCHAR2(B, 100),
	VOLUMENTICKET VARCHAR2(B, 100),
	FOLIOINTERNO VARCHAR2(B, 100),
	VOLUMENNOTA VARCHAR2(B, 100),
	COINCIDEVOLUMEN VARCHAR2(B, 100)
)
/
CREATE TABLE EAI.LDR_SO_HANDY
( 
	SAP_CUSTOMER_CLEAN VARCHAR2(B, 50),
	SKU_CODE VARCHAR2(B, 50),
	WEEK_START VARCHAR2(B, 50),
	SUGGESTED_ORDER VARCHAR2(B, 50),
	PLANT VARCHAR2(B, 10)
)
/
CREATE TABLE EAI.LDR_SO_IVY
( 
	RETAILER__C VARCHAR2(B, 50),
	MARKET_ISO__C VARCHAR2(B, 4),
	PRODUCT__C VARCHAR2(B, 50),
	QUANTITY__C VARCHAR2(B, 50),
	RECORDTYPEID VARCHAR2(B, 50),
	OWNERID VARCHAR2(B, 50),
	MIGRATION_EXTERNAL_ID__C VARCHAR2(B, 50),
	WEEK_START VARCHAR2(B, 50)
)
/
CREATE TABLE EAI.LOG_PEDIDOS_EDI
( 
	CLIENTE VARCHAR2(B, 10),
	CADENA VARCHAR2(B, 10),
	PEDIDO VARCHAR2(B, 15),
	FECHA DATE DEFAULT sysdate
)
/
CREATE TABLE EAI.LOG_T3R_SALES_DOCS_OLD
( 
	FECHA DATE,
	USUARIO VARCHAR2(B, 30),
	USUARIO_RED VARCHAR2(B, 30),
	IP VARCHAR2(B, 30),
	TERMINAL VARCHAR2(B, 40),
	DOC_NUM_R3 VARCHAR2(B, 10),
	CAMBIO VARCHAR2(B, 2000),
	TICKET_REFERENCIA VARCHAR2(B, 30)
)
/
CREATE TABLE EAI.MX_AUDIT_GPS_VENTA
( 
	CTRO VARCHAR2(B, 4),
	UBICACION VARCHAR2(C, 4),
	LOGIN VARCHAR2(C, 50) NOT NULL,
	INVC_DT DATE,
	DOC_NUM VARCHAR2(C, 125),
	TTL_INVC_AMT NUMBER(22, 7),
	V3_INVQTY NUMBER,
	STATUS_CD VARCHAR2(C, 30),
	LOC VARCHAR2(C, 50),
	OU_NUM VARCHAR2(C, 30),
	X_GPS_XCOORD NUMBER(22, 7),
	X_GPS_YCOORD NUMBER(22, 7),
	PRIMER_DOCUMENTO DATE,
	CREATED DATE,
	DATE_EVENT DATE,
	LATITUDE VARCHAR2(B, 30),
	LONGITUDE VARCHAR2(B, 30),
	MINUTOS NUMBER(4, 0),
	ROW_ID VARCHAR2(B, 30)
)
/
CREATE TABLE EAI.MX_DATOS_CLIENTE
( 
	RFC VARCHAR2(B, 20),
	CADENA VARCHAR2(B, 10),
	RAZON_SOCIAL VARCHAR2(B, 100),
	CREDITO NUMBER(3, 0),
	CANAL VARCHAR2(B, 30),
	TELEBOX VARCHAR2(B, 30),
	FORMA_PAGO VARCHAR2(B, 30),
	METODO_PAGO VARCHAR2(B, 30),
	REF_BANCARIA VARCHAR2(B, 30),
	LP_NAL VARCHAR2(B, 2),
	LP_DF VARCHAR2(B, 2),
	LP_FRONT VARCHAR2(B, 2),
	IVA_NAL VARCHAR2(B, 2),
	IVA_FRONT VARCHAR2(B, 2),
	LP_ESPECIAL VARCHAR2(B, 2),
	CADENA_SAP VARCHAR2(B, 2),
	TIPO_CLTE VARCHAR2(B, 30),
	SUBTIPO_CLTE VARCHAR2(B, 30)
)
/
CREATE TABLE EAI.MX_DELIVERY_OPEN
( 
	TERR VARCHAR2(B, 4),
	MATERIAL VARCHAR2(B, 10),
	CANTIDAD_VTA NUMBER(14, 0)
)
/
CREATE TABLE EAI.MX_GPS_POLLING
( 
	DATE_EVT VARCHAR2(B, 30),
	LATITUDE VARCHAR2(B, 30),
	LONGITUDE VARCHAR2(B, 30),
	SATELLITE VARCHAR2(B, 30),
	EVENT VARCHAR2(B, 30),
	CREATED VARCHAR2(B, 30),
	CREATEDBY VARCHAR2(B, 30),
	UPDATED VARCHAR2(B, 30),
	UPDATEDBY VARCHAR2(B, 30),
	PROCESADO VARCHAR2(B, 30),
	DATE_EVENT DATE
)
/
CREATE TABLE EAI.MX_NOTA_CREDITO_CFG
( 
	SERIE VARCHAR2(B, 5),
	FOLIO NUMBER(8, 0),
	PORCENTAJE NUMBER(5, 2),
	FECHA VARCHAR2(B, 10)
)
/
CREATE TABLE EAI.MX10_APLICACION_CM_LDR
( 
	ROW_ID VARCHAR2(B, 20),
	FECHA_DOCUMENTO VARCHAR2(B, 20),
	TIPO_DOCUMENTO VARCHAR2(B, 20),
	SOCIEDAD VARCHAR2(B, 20),
	MONEDA VARCHAR2(B, 20),
	NUMERO_DOCUMENTO VARCHAR2(B, 20),
	MONTO_APLICAR VARCHAR2(B, 20),
	TEXTO VARCHAR2(B, 20),
	NOTA_CREDITO VARCHAR2(B, 20)
)
/
CREATE TABLE EAI.MX10_APLICACION_COBZA_LDR
( 
	ROW_ID VARCHAR2(B, 20),
	FECHA_DOCUMENTO VARCHAR2(B, 20),
	TIPO_DOCUMENTO VARCHAR2(B, 20),
	SOCIEDAD VARCHAR2(B, 20),
	MONEDA VARCHAR2(B, 20),
	CLAVE_CONTABILIZACION VARCHAR2(B, 4),
	CUENTA_BANCO VARCHAR2(B, 20),
	MONTO_APLICAR VARCHAR2(B, 20),
	ASIGNACION VARCHAR2(B, 30),
	TEXTO VARCHAR2(B, 60),
	DOCUMENTO VARCHAR2(B, 20),
	MONTO_APLICAR_2 VARCHAR2(B, 20),
	ASIGNACION_2 VARCHAR2(B, 20),
	TEXTO_2 VARCHAR2(B, 60),
	CUSTOMER VARCHAR2(B, 20),
	FECHA_VENCIMIENTO VARCHAR2(B, 20),
	DOCUMENTO_COMPENSACION VARCHAR2(B, 20),
	FECHA_COMPENSACION VARCHAR2(B, 20)
)
/
CREATE TABLE EAI.NEW_USERS
( 
	ONEID NVARCHAR2(300),
	WINDOWSID NVARCHAR2(300),
	NOMBRE NVARCHAR2(300),
	EMAIL NVARCHAR2(300)
)
/
CREATE TABLE EAI.OUT_CTRL
( 
	DISTRIBUIDOR NUMBER(4, 0) NOT NULL,
	STAGE NUMBER(2, 0) NOT NULL,
	T3_READY CHAR(B, 1) NOT NULL,
	BC_READY CHAR(B, 1) NOT NULL,
	LAST_START DATE DEFAULT SYSDATE,
	LAST_END DATE DEFAULT SYSDATE,
	ERROR CHAR(B, 1) DEFAULT 'N',
	INSTAGE VARCHAR2(B, 3) DEFAULT '000',
	CTRO VARCHAR2(B, 4),
	PROCESS VARCHAR2(B, 2),
	PROCESS_V3 VARCHAR2(B, 2)
)
/
CREATE TABLE EAI.PAYMENT_ERROR_LOG
( 
	CUST_ID VARCHAR2(B, 15) NOT NULL,
	INVOICE_NUM VARCHAR2(B, 15) NOT NULL,
	PAY_ID VARCHAR2(B, 15) NOT NULL,
	ERROR VARCHAR2(B, 100),
	PAY_DATE DATE NOT NULL,
	"VALUE" NUMBER(10, 2),
	CUST_INTEGRATION_ID VARCHAR2(B, 30)
)
/
CREATE TABLE EAI.RESPUESTA_SAT
( 
	RENGLON VARCHAR2(B, 6),
	RFC VARCHAR2(B, 15),
	STATUS VARCHAR2(B, 10)
)
/
CREATE TABLE EAI.RFC_VALIDADOS
( 
	RFC VARCHAR2(B, 15),
	FECHA DATE,
	RESPONSABLE VARCHAR2(B, 30)
)
/
CREATE TABLE EAI.SDC_3_CITY_CARGA_LDR
( 
	MES_ID NUMBER(6, 0),
	CADENA VARCHAR2(B, 25),
	PLAZA_DES VARCHAR2(B, 25),
	PLAZA_CVE VARCHAR2(B, 25),
	TIENDA_DES VARCHAR2(B, 25),
	TIENDA_CVE VARCHAR2(B, 25),
	UPC VARCHAR2(B, 25),
	DESCRIPCION VARCHAR2(B, 100),
	UDS_VTA NUMBER(10, 0),
	PESOS_VTA NUMBER(10, 2)
)
/
CREATE TABLE EAI.SDC_BITACORA_PROCESO
( 
	FECHA DATE,
	DESC_PROCESO VARCHAR2(B, 50)
)
/
CREATE TABLE EAI.SDC_CADENA
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	DESCRIPCION VARCHAR2(B, 100),
	CLIENTE_V3 VARCHAR2(B, 18)
)
/
CREATE TABLE EAI.SDC_CADENA_UPC
( 
	CADENA VARCHAR2(B, 10) NOT NULL,
	UPC_CTE VARCHAR2(B, 15) NOT NULL,
	UPC_SAP VARCHAR2(B, 15) NOT NULL,
	CODIGO_BARRAS_PRES_2 VARCHAR2(B, 20),
	CODIGO_BARRAS_PRES_3 VARCHAR2(B, 20),
	CODIGO_BARRAS_PRES_4 VARCHAR2(B, 20),
	UNIDAD_MED_VTA VARCHAR2(B, 3),
	VIGENCIA DATE
)
/
CREATE TABLE EAI.SDC_CADENAS_CARGA
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	MES_ID NUMBER(8, 0) NOT NULL,
	PLAZA_DES VARCHAR2(B, 25) NOT NULL,
	UPC VARCHAR2(B, 25) NOT NULL,
	DESCRIPCION VARCHAR2(B, 100),
	DETERMINANTE VARCHAR2(B, 25),
	UDS_VTA NUMBER(10, 0) NOT NULL,
	PESOS_VTA NUMBER(10, 2),
	FECHA_CARGA DATE
)
/
CREATE TABLE EAI.SDC_CARGA
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	CEDIS VARCHAR2(B, 25) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	TIENDA VARCHAR2(B, 100) NOT NULL,
	NOMBRE_TIENDA VARCHAR2(B, 100),
	ANIO NUMBER(4, 0) NOT NULL,
	SEMANA NUMBER(2, 0) NOT NULL,
	UPC VARCHAR2(B, 25) NOT NULL,
	DESCRIPCION VARCHAR2(B, 100),
	UNIDADES_RECIBIDAS NUMBER(10, 0),
	UNIDADES_VENDIDAS NUMBER(10, 0)
)
/
CREATE TABLE EAI.SDC_CARGA_DIA
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	CEDIS VARCHAR2(B, 25) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	TIENDA VARCHAR2(B, 25) NOT NULL,
	NOMBRE_TIENDA VARCHAR2(B, 100),
	FECHA NUMBER(10, 0) NOT NULL,
	UPC VARCHAR2(B, 25) NOT NULL,
	DESCRIPCION VARCHAR2(B, 100),
	UNIDADES_VENTA NUMBER(10, 0),
	PESOS_VENTA NUMBER(15, 2)
)
/
CREATE TABLE EAI.SDC_CARGA_DIA_LDR
( 
	TIEMPO_ID NUMBER(10, 0),
	NEGOCIO_DES VARCHAR2(B, 100),
	PLAZA_DES VARCHAR2(B, 25),
	PLAZA_CVE VARCHAR2(B, 25),
	TIENDA_DES VARCHAR2(B, 100),
	TIENDA_CVE VARCHAR2(B, 25),
	UPC_CVE VARCHAR2(B, 25),
	PRODUCTO_DES_LONG VARCHAR2(B, 100),
	UDSCMP NUMBER(10, 0),
	UDSVTA NUMBER(10, 2)
)
/
CREATE TABLE EAI.SDC_CARGA_LDR
( 
	CADENA VARCHAR2(B, 25),
	MES_ID NUMBER(8, 0),
	PLAZA_DES VARCHAR2(B, 25),
	UPC VARCHAR2(B, 25),
	DESCRIPCION VARCHAR2(B, 100),
	DETERMINANTE VARCHAR2(B, 25),
	UDS_VTA NUMBER(10, 0),
	PESOS_VTA NUMBER(10, 2)
)
/
CREATE TABLE EAI.SDC_CARGA_MEN_LDR
( 
	SEMANA_ID NUMBER(6, 0),
	NEGOCIO_DES VARCHAR2(B, 100),
	PLAZA_DES VARCHAR2(B, 25),
	PLAZA_CVE VARCHAR2(B, 25),
	TIENDA_DES VARCHAR2(B, 100),
	TIENDA_CVE VARCHAR2(B, 25),
	UPC_CVE VARCHAR2(B, 25),
	PRODUCTO_DES_LONG VARCHAR2(B, 100),
	UDSCMP NUMBER(10, 0),
	UDSVTA NUMBER(10, 0)
)
/
CREATE TABLE EAI.SDC_CARGA_MEN_PDV_F
( 
	CADENA VARCHAR2(B, 25),
	CEDIS VARCHAR2(B, 25),
	ANIOMES NUMBER(6, 0),
	PLAZA_CVE VARCHAR2(B, 25),
	PLAZA_DES VARCHAR2(B, 100),
	TIENDA_CVE VARCHAR2(B, 25),
	TIENDA_DES VARCHAR2(B, 100),
	UPC_CVE VARCHAR2(B, 25),
	PROD_DES_LONG VARCHAR2(B, 100),
	UDS_VTA NUMBER(10, 0),
	PESOS_VTA NUMBER(12, 2)
)
/
CREATE TABLE EAI.SDC_CARGA_MEN_PDV_LDR
( 
	PLAZA_CVE VARCHAR2(B, 25),
	PLAZA_DES VARCHAR2(B, 100),
	TIENDA_DES VARCHAR2(B, 100),
	TIENDA_CVE VARCHAR2(B, 25),
	UPC_CVE VARCHAR2(B, 25),
	PROD_DES_LONG VARCHAR2(B, 100),
	PROPIETARIOMARCA_DES VARCHAR2(B, 100),
	MES_ID NUMBER(6, 0),
	UDS_VTA NUMBER(10, 0),
	PESOS_VTA NUMBER(12, 2)
)
/
CREATE TABLE EAI.SDC_CARGA_SEM_LDR
( 
	SEMANA_ID NUMBER(6, 0),
	NEGOCIO_DES VARCHAR2(B, 100),
	PLAZA_DES VARCHAR2(B, 25),
	PLAZA_CVE VARCHAR2(B, 25),
	TIENDA_DES VARCHAR2(B, 100),
	TIENDA_CVE VARCHAR2(B, 100),
	UPC_CVE VARCHAR2(B, 25),
	PRODUCTO_DES_LONG VARCHAR2(B, 100),
	UDSCMP NUMBER(10, 0),
	UDSVTA NUMBER(10, 0)
)
/
CREATE TABLE EAI.SDC_CARGA_TEMP
( 
	CADENA VARCHAR2(B, 25),
	CEDIS VARCHAR2(B, 25),
	ANIOMES NUMBER(6, 0),
	PLAZA_CVE VARCHAR2(B, 25),
	PLAZA_DES VARCHAR2(B, 150),
	TIENDA_CVE VARCHAR2(B, 25),
	TIENDA_DES VARCHAR2(B, 150),
	UPC_CVE VARCHAR2(B, 25),
	PROD_DES_LONG VARCHAR2(B, 200),
	UDS_VTA NUMBER(20, 0),
	PESOS_VTA NUMBER(12, 2)
)
/
CREATE TABLE EAI.SDC_CARGA_VENTA
( 
	CADENA VARCHAR2(B, 25),
	ANIOMES NUMBER(6, 0),
	PLAZA VARCHAR2(B, 25),
	CODIGO_BARRAS VARCHAR2(B, 25),
	PRODUCTO VARCHAR2(B, 100),
	UNIDADES NUMBER(10, 0),
	VENTA NUMBER(12, 2)
)
/
CREATE TABLE EAI.SDC_CARGA_VENTA_BKP
( 
	CADENA VARCHAR2(B, 25),
	ANIOMES NUMBER(6, 0),
	PLAZA VARCHAR2(B, 25),
	CODIGO_BARRAS VARCHAR2(B, 25),
	PRODUCTO VARCHAR2(B, 100),
	UNIDADES NUMBER(10, 0),
	VENTA NUMBER(12, 2)
)
/
CREATE TABLE EAI.SDC_CEDIS
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	CEDIS VARCHAR2(B, 25) NOT NULL,
	DESCRIPCION VARCHAR2(B, 100),
	CLIENTE_V3 VARCHAR2(B, 18)
)
/
CREATE TABLE EAI.SDC_DIST_VENTA_SEM
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	CEDIS VARCHAR2(B, 25) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	TIENDA VARCHAR2(B, 25) NOT NULL,
	ANIO NUMBER(4, 0) NOT NULL,
	SEMANA NUMBER(2, 0) NOT NULL,
	UPC VARCHAR2(B, 25),
	MATERIAL VARCHAR2(B, 18) NOT NULL,
	DESCRIPCION VARCHAR2(B, 100),
	UNIDADES_RECIBIDAS NUMBER(10, 0),
	UNIDADES_VENDIDAS NUMBER(10, 0),
	RELACION_PDTE CHAR(B, 1)
)
/
CREATE TABLE EAI.SDC_DIST_VTA_SEM_16_53_Y_2_33
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	CEDIS VARCHAR2(B, 25) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	TIENDA VARCHAR2(B, 25) NOT NULL,
	ANIO NUMBER(4, 0) NOT NULL,
	SEMANA NUMBER(2, 0) NOT NULL,
	UPC VARCHAR2(B, 25),
	MATERIAL VARCHAR2(B, 18) NOT NULL,
	DESCRIPCION VARCHAR2(B, 100),
	UNIDADES_RECIBIDAS NUMBER(10, 0),
	UNIDADES_VENDIDAS NUMBER(10, 0),
	RELACION_PDTE CHAR(B, 1)
)
/
CREATE TABLE EAI.SDC_DIST_VTA_V3CEDIS_RESP
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	CEDIS VARCHAR2(B, 25) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	TIENDA VARCHAR2(B, 25) NOT NULL,
	ANIO NUMBER(4, 0) NOT NULL,
	SEMANA NUMBER(2, 0) NOT NULL,
	UPC VARCHAR2(B, 20),
	MATERIAL VARCHAR2(B, 18) NOT NULL,
	DESCRIPCION VARCHAR2(B, 100),
	UNIDADES_RECIBIDAS NUMBER(10, 0),
	UNIDADES_VENDIDAS NUMBER(10, 0),
	RELACION_PDTE CHAR(B, 1),
	CLIENTE_V3 VARCHAR2(B, 18),
	CADENA_V3 VARCHAR2(B, 18),
	CEDIS_V3 VARCHAR2(B, 18)
)
/
CREATE TABLE EAI.SDC_DISTR_VENTA_V3CEDIS_RESP
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	CEDIS VARCHAR2(B, 25) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	TIENDA VARCHAR2(B, 25) NOT NULL,
	ANIO NUMBER(4, 0) NOT NULL,
	SEMANA NUMBER(2, 0) NOT NULL,
	UPC VARCHAR2(B, 20),
	MATERIAL VARCHAR2(B, 18) NOT NULL,
	DESCRIPCION VARCHAR2(B, 100),
	UNIDADES_RECIBIDAS NUMBER(10, 0),
	UNIDADES_VENDIDAS NUMBER(10, 0),
	RELACION_PDTE CHAR(B, 1),
	CLIENTE_V3 VARCHAR2(B, 18),
	CADENA_V3 VARCHAR2(B, 18),
	CEDIS_V3 VARCHAR2(B, 18)
)
/
CREATE TABLE EAI.SDC_DISTRIBUCION_VENTA
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	CEDIS VARCHAR2(B, 25) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	TIENDA VARCHAR2(B, 100) NOT NULL,
	ANIO NUMBER(4, 0) NOT NULL,
	SEMANA NUMBER(2, 0) NOT NULL,
	UPC VARCHAR2(B, 25),
	MATERIAL VARCHAR2(B, 18) NOT NULL,
	DESCRIPCION VARCHAR2(B, 100),
	UNIDADES_RECIBIDAS NUMBER(10, 0),
	UNIDADES_VENDIDAS NUMBER(10, 0),
	RELACION_PDTE CHAR(B, 1)
)
/
CREATE TABLE EAI.SDC_ERROR
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	TIENDA VARCHAR2(B, 100) NOT NULL,
	ANIO NUMBER(4, 0) NOT NULL,
	SEMANA NUMBER(2, 0) NOT NULL,
	NO_ERROR NUMBER(2, 0) NOT NULL,
	ERROR VARCHAR2(B, 500) NOT NULL
)
/
CREATE TABLE EAI.SDC_ERROR_DIARIA
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	TIENDA VARCHAR2(B, 25) NOT NULL,
	FECHA NUMBER(10, 0) NOT NULL,
	NO_ERROR NUMBER(2, 0) NOT NULL,
	ERROR VARCHAR2(B, 500) NOT NULL
)
/
CREATE TABLE EAI.SDC_ERROR_PDV
( 
	CADENA VARCHAR2(B, 25),
	TIENDA VARCHAR2(B, 100),
	ANIOMES NUMBER(6, 0),
	ERROR VARCHAR2(B, 800),
	TIPO NUMBER(10, 0),
	PLAZA VARCHAR2(B, 100)
)
/
CREATE TABLE EAI.SDC_ERROR_PUNTO_VENTA
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	ERROR VARCHAR2(B, 100) NOT NULL,
	ANIOSEM NUMBER(6, 0) NOT NULL,
	TIENDA VARCHAR2(B, 25) NOT NULL,
	UPC VARCHAR2(B, 25) NOT NULL,
	UDS_VTA NUMBER(10, 0),
	PESOS_VTA NUMBER(10, 2)
)
/
CREATE TABLE EAI.SDC_ERROR_VENTA
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	ANIOMES NUMBER(6, 0) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	ERROR VARCHAR2(B, 500) NOT NULL
)
/
CREATE TABLE EAI.SDC_ERROR_VTA_CAD
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	ANIOMES NUMBER(6, 0) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	ERROR VARCHAR2(B, 500) NOT NULL
)
/
CREATE TABLE EAI.SDC_GRABA_BITACORA
( 
	PROCESO VARCHAR2(B, 20),
	FECHA DATE,
	STATUS VARCHAR2(B, 20),
	MENSAJE VARCHAR2(B, 600)
)
/
CREATE TABLE EAI.SDC_HISTORIA
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	CEDIS VARCHAR2(B, 25) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	TIENDA VARCHAR2(B, 25) NOT NULL,
	ANIO NUMBER(4, 0) NOT NULL,
	MES NUMBER(2, 0) NOT NULL,
	MATERIAL VARCHAR2(B, 18) NOT NULL,
	UNIDADES_RECIBIDAS NUMBER(10, 0),
	UNIDADES_VENDIDAS NUMBER(10, 0)
)
/
CREATE TABLE EAI.SDC_MATERIAL
( 
	MATERIAL VARCHAR2(B, 18) NOT NULL,
	NOMBRE_MATERIAL VARCHAR2(B, 80) NOT NULL,
	NOMBRE_CORTO VARCHAR2(B, 15),
	CONVERSION_PRES_2_A_1 NUMBER(4, 0),
	CONVERSION_PRES_3_A_2 NUMBER(4, 0),
	CONVERSION_PRES_4_A_3 NUMBER(4, 0),
	CODIGO_BARRAS_PRES_2 VARCHAR2(B, 20),
	CODIGO_BARRAS_PRES_3 VARCHAR2(B, 20),
	CODIGO_BARRAS_PRES_4 VARCHAR2(B, 20),
	UNIDAD_MED_VTA VARCHAR2(B, 3),
	CIA VARCHAR2(B, 30),
	CIG_X_CLL NUMBER(6, 0),
	DEN_CIG_X_CLL NUMBER(6, 0),
	CIG_X_CT NUMBER(6, 0),
	DEN_CIG_X_CT NUMBER(6, 0),
	CIG_X_PAQ NUMBER(6, 0),
	DEN_CIG_X_PAQ NUMBER(6, 0),
	UM VARCHAR2(B, 3),
	CREACION DATE,
	MODIFICACION DATE
)
/
CREATE TABLE EAI.SDC_OXXO_DUNHILL_DIARIO
( 
	SEMANA_ID NUMBER(10, 0) NOT NULL,
	NEGOCIO_DES VARCHAR2(B, 10) NOT NULL,
	PLAZA_DES VARCHAR2(B, 30),
	PLAZA_CVE VARCHAR2(B, 10),
	TIENDA_DES VARCHAR2(B, 30),
	TIENDA_CVE VARCHAR2(B, 10),
	UPC_CVE VARCHAR2(B, 15) NOT NULL,
	PRODUCTO_DES_LONG VARCHAR2(B, 100),
	UDSCMP NUMBER(12, 2),
	UDSVTA NUMBER(12, 2),
	SKU VARCHAR2(B, 15)
)
/
CREATE TABLE EAI.SDC_PLAZA
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	CEDIS VARCHAR2(B, 25) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	DESCRIPCION VARCHAR2(B, 100),
	ACTIVA NUMBER(1, 0)
)
/
CREATE TABLE EAI.SDC_PLAZA_NUEVA
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	CEDIS VARCHAR2(B, 25) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	DESCRIPCION VARCHAR2(B, 100)
)
/
CREATE TABLE EAI.SDC_PROCESO
( 
	ID_PROCESO NUMBER NOT NULL,
	DESC_PROCESO VARCHAR2(B, 30),
	RUTA_FTP VARCHAR2(B, 100),
	PROC_ORACLE VARCHAR2(B, 25),
	PROC_INI DATE,
	PROC_FIN DATE,
	COMENTARIO VARCHAR2(B, 100)
)
/
CREATE TABLE EAI.SDC_PTO_VTA_V3CEDIS_RESP
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	ANIOSEM NUMBER(6, 0) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	SKU NUMBER(18, 0) NOT NULL,
	VALOR_VENTA NUMBER(12, 2),
	VOLUMEN_VENTA NUMBER(12, 0),
	VOLUMEN_VENTA_CLL NUMBER(12, 0),
	TIENDA VARCHAR2(B, 25) NOT NULL
)
/
CREATE TABLE EAI.SDC_PUNTO_VENTA
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	SKU NUMBER(18, 0) NOT NULL,
	VALOR_VENTA NUMBER(12, 2),
	VOLUMEN_VENTA NUMBER(12, 0),
	VOLUMEN_VENTA_CLL NUMBER(12, 0),
	ANIOSEM NUMBER(6, 0) NOT NULL,
	TIENDA VARCHAR2(B, 25) NOT NULL
)
/
CREATE TABLE EAI.SDC_RUTA_CARGA
( 
	PROCESO VARCHAR2(B, 25),
	RUTA_CARGA VARCHAR2(B, 100)
)
/
CREATE TABLE EAI.SDC_SKU_DE_PARA
( 
	DE NUMBER(12, 0) NOT NULL,
	PARA NUMBER(12, 0) NOT NULL
)
/
CREATE TABLE EAI.SDC_TIENDA
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	CEDIS VARCHAR2(B, 25) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	TIENDA VARCHAR2(B, 100) NOT NULL,
	DESCRIPCION VARCHAR2(B, 100),
	CLIENTE_V3 VARCHAR2(B, 18)
)
/
CREATE TABLE EAI.SDC_TIENDA_NUEVA
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	CEDIS VARCHAR2(B, 25) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	TIENDA VARCHAR2(B, 25) NOT NULL,
	DESCRIPCION VARCHAR2(B, 100),
	CLIENTE_V3 VARCHAR2(B, 18)
)
/
CREATE TABLE EAI.SDC_TIENDA_TEST
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	CEDIS VARCHAR2(B, 25) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	TIENDA VARCHAR2(B, 25) NOT NULL,
	DESCRIPCION VARCHAR2(B, 100),
	CLIENTE_V3 VARCHAR2(B, 18)
)
/
CREATE TABLE EAI.SDC_TIENDAS_MADURAS
( 
	PLAZA_CVE VARCHAR2(B, 25),
	PLAZA_DES VARCHAR2(B, 100),
	TIENDA_CVE VARCHAR2(B, 25)
)
/
CREATE TABLE EAI.SDC_TIENDAS_MADURAS_LDR
( 
	PLAZA_CVE VARCHAR2(B, 25),
	PLAZA_DES VARCHAR2(B, 100),
	TIENDA_CVE VARCHAR2(B, 25)
)
/
CREATE TABLE EAI.SDC_VENTA
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	ANIOMES NUMBER(6, 0) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	SKU NUMBER(18, 0) NOT NULL,
	VALOR_VENTA NUMBER(12, 2),
	VOLUMEN_VENTA NUMBER(12, 0),
	VOLUMEN_VENTA_CLL NUMBER(12, 0)
)
/
CREATE TABLE EAI.SDC_VENTA_MEN_PDV
( 
	CADENA VARCHAR2(B, 25),
	CEDIS VARCHAR2(B, 25),
	ANIOMES NUMBER(6, 0),
	PLAZA_CVE VARCHAR2(B, 25),
	PLAZA_DES VARCHAR2(B, 100),
	TIENDA_CVE VARCHAR2(B, 25),
	TIENDA_DES VARCHAR2(B, 100),
	UPC_CVE VARCHAR2(B, 25),
	SKU NUMBER(18, 0) NOT NULL,
	PROD_DES_LONG VARCHAR2(B, 100),
	UDS_VTA NUMBER(10, 0),
	UDS_VTA_CLL NUMBER(10, 0),
	PESOS_VTA NUMBER(12, 2),
	TIENDA_MADURA NVARCHAR2(1)
)
/
CREATE TABLE EAI.SDC_VTA_V3CEDIS_RESP
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	ANIOMES NUMBER(6, 0) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	SKU NUMBER(18, 0) NOT NULL,
	VALOR_VENTA NUMBER(12, 2),
	VOLUMEN_VENTA NUMBER(12, 0),
	VOLUMEN_VENTA_CLL NUMBER(12, 0)
)
/
CREATE TABLE EAI.SEVEN_INVENTARIO_LDR
( 
	PERIODO NUMBER(10, 0),
	PLAZA NUMBER(10, 0),
	MERCADO NUMBER(10, 0),
	CAMPO NUMBER(10, 0),
	NUM_TIENDA VARCHAR2(B, 50),
	TIENDA VARCHAR2(B, 255),
	SKU VARCHAR2(B, 255),
	UPC VARCHAR2(B, 255),
	ARTICULO VARCHAR2(B, 255),
	UDS_INVT NUMBER(10, 0),
	UPTD NUMBER(10, 5),
	DELISTING NUMBER(1, 0),
	AREA VARCHAR2(B, 40),
	TERRITORIO VARCHAR2(B, 20),
	DIA VARCHAR2(B, 10)
)
/
CREATE TABLE EAI.SEVEN_PROCESO
( 
	ID_PROCESO NUMBER(10, 0) NOT NULL,
	DESC_PROCESO VARCHAR2(B, 30),
	PROC_ORACLE VARCHAR2(B, 30),
	PROC_INI DATE,
	PROC_FIN DATE,
	COMENTARIO VARCHAR2(B, 100)
)
/
CREATE TABLE EAI.T3R_CARTERA_SAP_LDR
( 
	CLIENTE VARCHAR2(B, 10),
	DISTRIBUIDOR VARCHAR2(B, 4),
	REFERENCIA VARCHAR2(B, 18),
	FECHA_DOC VARCHAR2(B, 8),
	TIPO_DOC VARCHAR2(B, 2),
	MONTO NUMBER(13, 2),
	DIAS_CDTO NUMBER(3, 0),
	CARGO VARCHAR2(B, 1)
)
/
CREATE TABLE EAI.T3R_CARTERA_SAP_OLD
( 
	CLIENTE VARCHAR2(B, 10),
	DISTRIBUIDOR VARCHAR2(B, 4),
	REFERENCIA VARCHAR2(B, 30),
	FECHA_DOC VARCHAR2(B, 8),
	TIPO_DOC VARCHAR2(B, 2),
	MONTO NUMBER(13, 2),
	DIAS_CDTO NUMBER(3, 0),
	ASIGNACION VARCHAR2(B, 30)
)
/
CREATE TABLE EAI.T3R_REPORTE_STOCK_TAO
( 
	PARTNER_ID VARCHAR2(B, 1024),
	PARTNER_NAME VARCHAR2(B, 1024),
	UBICACION VARCHAR2(B, 1024),
	PLANTA VARCHAR2(B, 1024),
	MATERIAL VARCHAR2(B, 15),
	MATERIAL_NAME VARCHAR2(B, 1024),
	LOTE VARCHAR2(B, 1024),
	LIBRE_UTILIZACION NUMBER(15, 3),
	EN_CONTROL NUMBER(15, 3),
	STOCK_NO_LIBRE NUMBER(15, 3),
	EN_TRASLADO NUMBER(15, 3),
	CANTIDAD NUMBER(15, 3),
	CANTIDAD_LB10 NUMBER(15, 3),
	UMB VARCHAR2(B, 1024),
	STATUS VARCHAR2(B, 10) DEFAULT 'GOOD'
)
/
CREATE TABLE EAI.T3R_SALES_DOCS
( 
	DOC_DATE VARCHAR2(B, 8),
	DISTRIBUTOR VARCHAR2(B, 4),
	CUSTOMER NUMBER(10, 0),
	DOC_NUM_R3 VARCHAR2(B, 20),
	DOC_ORD_R3 VARCHAR2(B, 20),
	DOC_NUM_REF1 VARCHAR2(B, 20),
	DOC_NUM_REF2 VARCHAR2(B, 20),
	DOC_TYPE VARCHAR2(B, 4),
	DOC_STATUS VARCHAR2(B, 1),
	DOC_NETAMT NUMBER(13, 2),
	DOC_TAXAMT NUMBER(13, 2),
	DOC_QTY NUMBER(13, 2)
)
/
CREATE TABLE EAI.T3R_SALES_DOCS_LDR
( 
	DOC_DATE VARCHAR2(B, 8),
	DISTRIBUTOR VARCHAR2(B, 4),
	CUSTOMER NUMBER(10, 0),
	DOC_NUM_R3 VARCHAR2(B, 20),
	DOC_ORD_R3 VARCHAR2(B, 20),
	DOC_NUM_REF1 VARCHAR2(B, 20),
	DOC_NUM_REF2 VARCHAR2(B, 20),
	DOC_TYPE VARCHAR2(B, 4),
	DOC_STATUS VARCHAR2(B, 1),
	DOC_NETAMT NUMBER(13, 2),
	DOC_TAXAMT NUMBER(13, 2),
	DOC_QTY NUMBER(13, 2)
)
/
CREATE TABLE EAI.T3R_SALES_DOCS_LDR_FMO
( 
	DOC_DATE VARCHAR2(B, 8),
	DISTRIBUTOR VARCHAR2(B, 4),
	CUSTOMER NUMBER(10, 0),
	DOC_NUM_R3 VARCHAR2(B, 20),
	DOC_ORD_R3 VARCHAR2(B, 20),
	DOC_NUM_REF1 VARCHAR2(B, 20),
	DOC_NUM_REF2 VARCHAR2(B, 20),
	DOC_TYPE VARCHAR2(B, 4),
	DOC_STATUS VARCHAR2(B, 1),
	DOC_NETAMT NUMBER(13, 2),
	DOC_TAXAMT NUMBER(13, 2),
	DOC_QTY NUMBER(13, 2)
)
/
CREATE TABLE EAI.T3R_SALES_DOCS_LDR_MX01
( 
	DOC_DATE VARCHAR2(B, 8),
	DISTRIBUTOR VARCHAR2(B, 4),
	CUSTOMER VARCHAR2(B, 10),
	DOC_NUM_R3 VARCHAR2(B, 20),
	DOC_ORD_R3 VARCHAR2(B, 20),
	DOC_NUM_REF1 VARCHAR2(B, 20),
	DOC_NUM_REF2 VARCHAR2(B, 20),
	DOC_TYPE VARCHAR2(B, 4),
	DOC_STATUS VARCHAR2(B, 1),
	DOC_NETAMT NUMBER(13, 2),
	DOC_TAXAMT NUMBER(13, 2),
	DOC_QTY NUMBER(13, 2),
	CREATED DATE
)
/
CREATE TABLE EAI.T3R_SALES_DOCS_MX01
( 
	DOC_DATE VARCHAR2(B, 8),
	DISTRIBUTOR VARCHAR2(B, 4),
	CUSTOMER VARCHAR2(B, 10),
	DOC_NUM_R3 VARCHAR2(B, 20),
	DOC_ORD_R3 VARCHAR2(B, 20),
	DOC_NUM_REF1 VARCHAR2(B, 20),
	DOC_NUM_REF2 VARCHAR2(B, 20),
	DOC_TYPE VARCHAR2(B, 4),
	DOC_STATUS VARCHAR2(B, 1),
	DOC_NETAMT NUMBER(13, 2),
	DOC_TAXAMT NUMBER(13, 2),
	DOC_QTY NUMBER(13, 2)
)
/
CREATE TABLE EAI.T3R_SALES_DOCS_MX06
( 
	DOC_DATE VARCHAR2(B, 8),
	DISTRIBUTOR VARCHAR2(B, 4),
	CUSTOMER VARCHAR2(B, 10),
	DOC_NUM_R3 VARCHAR2(B, 20),
	DOC_ORD_R3 VARCHAR2(B, 20),
	DOC_NUM_REF1 VARCHAR2(B, 20),
	DOC_NUM_REF2 VARCHAR2(B, 20),
	DOC_TYPE VARCHAR2(B, 4),
	DOC_STATUS VARCHAR2(B, 1),
	DOC_NETAMT NUMBER(13, 2),
	DOC_TAXAMT NUMBER(13, 2),
	DOC_QTY NUMBER(13, 2)
)
/
CREATE TABLE EAI.T3R_SALES_DOCS_OLD
( 
	DOC_DATE VARCHAR2(B, 8),
	DISTRIBUTOR VARCHAR2(B, 4),
	CUSTOMER NUMBER(10, 0),
	DOC_NUM_R3 VARCHAR2(B, 20),
	DOC_ORD_R3 VARCHAR2(B, 20),
	DOC_NUM_REF1 VARCHAR2(B, 30),
	DOC_NUM_REF2 VARCHAR2(B, 30),
	DOC_TYPE VARCHAR2(B, 4),
	DOC_STATUS VARCHAR2(B, 1),
	DOC_NETAMT NUMBER(13, 2),
	DOC_TAXAMT NUMBER(13, 2),
	DOC_QTY NUMBER(13, 2),
	CREATED DATE
)
/
CREATE TABLE EAI.T3R_SALES_DOCS_OTHERS
( 
	DOC_DATE VARCHAR2(B, 8),
	DISTRIBUTOR VARCHAR2(B, 4),
	CUSTOMER NUMBER(10, 0),
	DOC_NUM_R3 VARCHAR2(B, 20),
	DOC_ORD_R3 VARCHAR2(B, 20),
	DOC_NUM_REF1 VARCHAR2(B, 30),
	DOC_NUM_REF2 VARCHAR2(B, 30),
	DOC_TYPE VARCHAR2(B, 4),
	DOC_STATUS VARCHAR2(B, 1),
	DOC_NETAMT NUMBER(13, 2),
	DOC_TAXAMT NUMBER(13, 2),
	DOC_QTY NUMBER(13, 2),
	CREATED DATE
)
/
CREATE TABLE EAI.T3R_STATUS
( 
	"PROCEDURE" VARCHAR2(B, 50),
	START_DATE DATE,
	END_DATE DATE
)
/
CREATE TABLE EAI.T3R_STATUS_LOG
( 
	DATE_INSERT DATE,
	"PROCEDURE" VARCHAR2(B, 50),
	START_DATE DATE,
	END_DATE DATE
)
/
CREATE TABLE EAI.TAO_CARTERA_SAP_LDR
( 
	CLIENTE VARCHAR2(B, 10),
	TIPO_DOC VARCHAR2(B, 2),
	ASIGNACION VARCHAR2(B, 1024),
	FECHA_DOC VARCHAR2(B, 8),
	MONTO VARCHAR2(B, 20),
	MONTO_AUX VARCHAR2(B, 20),
	MONEDA VARCHAR2(B, 20),
	DIAS_CDTO VARCHAR2(B, 4),
	REFERENCIA VARCHAR2(B, 30),
	CARGO VARCHAR2(B, 1),
	ACCOUNTDOCUMENT VARCHAR2(B, 10),
	BRANCH_NUMBER VARCHAR2(B, 10)
)
/
CREATE TABLE EAI.TAO_JAULAS
( 
	CTRO VARCHAR2(B, 4),
	TERRITORIO VARCHAR2(B, 4),
	LGORT VARCHAR2(B, 4),
	RESPONSABLE VARCHAR2(B, 10)
)
/
CREATE TABLE EAI.TAO_SALES_DOCS_LDR
( 
	DOC_ORD_R3 VARCHAR2(B, 20),
	DOC_NUM_R3 VARCHAR2(B, 20),
	CUSTOMER_NUMBER NUMBER(10, 0),
	DISTRIBUTOR VARCHAR2(B, 4),
	CUSTOMER VARCHAR2(B, 20),
	DOC_DATE VARCHAR2(B, 8),
	DOC_TYPE VARCHAR2(B, 4),
	DOC_NUM_REF1 VARCHAR2(B, 30),
	DOC_NUM_REF2 VARCHAR2(B, 30),
	DOC_STATUS VARCHAR2(B, 1),
	DOC_NETAMT NUMBER(13, 3),
	DOC_TAXAMT NUMBER(13, 3),
	DOC_QTY NUMBER(13, 3)
)
/
CREATE TABLE EAI.TEXTOS
( 
	LEYENDA NUMBER(3, 0),
	TEXTO VARCHAR2(B, 100)
)
/
CREATE TABLE EAI.TMP_MX16_CENTRALIZADO
( 
	STATUS VARCHAR2(B, 20),
	TABLE_ROW VARCHAR2(B, 20),
	SEPARATOR VARCHAR2(B, 10),
	DOCUMENTDATE VARCHAR2(B, 20),
	POSTINGDATE VARCHAR2(B, 20),
	DOCUMENTTYPE VARCHAR2(B, 4),
	COMPANYCODE VARCHAR2(B, 4),
	CURRENCY VARCHAR2(B, 10),
	BILLINGDOCUMENT VARCHAR2(B, 10),
	REFERENCEDOCUMENT VARCHAR2(B, 20),
	DOCUMENTHEADERTEXT VARCHAR2(B, 40),
	CUSTOMER VARCHAR2(B, 20),
	ACCOUNT_GL VARCHAR2(B, 20),
	ITEMTEXT VARCHAR2(B, 40),
	ASSIGNMENT VARCHAR2(B, 20),
	PAYMENT NUMBER(17, 2),
	SEPARATOR2 VARCHAR2(B, 10),
	FISCALYEAR VARCHAR2(B, 4),
	INVOICEACCDOC VARCHAR2(B, 10),
	INVOICEAMOUNT VARCHAR2(B, 20),
	POSTINGCODE VARCHAR2(B, 4),
	SD_DOCUMENT VARCHAR2(B, 10),
	CLEARINGDOCUMENT VARCHAR2(B, 10),
	RESIDUALDOCUMENT VARCHAR2(B, 10),
	MESSAGETEXT VARCHAR2(B, 100),
	MSGTYPE VARCHAR2(B, 100),
	MSGCLAS VARCHAR2(B, 100),
	MSGNUMBER VARCHAR2(B, 100)
)
/
CREATE TABLE EAI.UPC_MATERIAL_PASO
( 
	UPC VARCHAR2(B, 20),
	SKU NUMBER(8, 0),
	MENSAJE VARCHAR2(B, 100),
	UMV VARCHAR2(B, 3),
	CLLXPAQ NUMBER(2, 0)
)
/
CREATE TABLE EAI.W_CEDIS_SDC_DIST
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	CEDIS VARCHAR2(B, 25) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	TIENDA VARCHAR2(B, 25) NOT NULL,
	ANIO NUMBER(4, 0) NOT NULL,
	SEMANA NUMBER(2, 0) NOT NULL,
	UPC VARCHAR2(B, 20),
	MATERIAL VARCHAR2(B, 18) NOT NULL,
	DESCRIPCION VARCHAR2(B, 100),
	UNIDADES_RECIBIDAS NUMBER(10, 0),
	UNIDADES_VENDIDAS NUMBER(10, 0),
	RELACION_PDTE CHAR(B, 1),
	CLIENTE_V3 VARCHAR2(B, 18),
	CADENA_V3 VARCHAR2(B, 18),
	CEDIS_V3 VARCHAR2(B, 18)
)
/
CREATE TABLE EAI.W_SDC_DIST
( 
	CADENA VARCHAR2(B, 25) NOT NULL,
	CEDIS VARCHAR2(B, 25) NOT NULL,
	PLAZA VARCHAR2(B, 25) NOT NULL,
	TIENDA VARCHAR2(B, 25) NOT NULL,
	ANIO NUMBER(4, 0) NOT NULL,
	SEMANA NUMBER(2, 0) NOT NULL,
	UPC VARCHAR2(B, 25),
	MATERIAL VARCHAR2(B, 18) NOT NULL,
	DESCRIPCION VARCHAR2(B, 100),
	UNIDADES_RECIBIDAS NUMBER(10, 0),
	UNIDADES_VENDIDAS NUMBER(10, 0),
	RELACION_PDTE CHAR(B, 1)
)
/
CREATE TABLE EAI.WA_CAMBIA_CENTRO
( 
	UBICACION VARCHAR2(B, 4),
	FECHAINICIO VARCHAR2(B, 8),
	FECHAFINAL VARCHAR2(B, 8),
	CTRO VARCHAR2(B, 4),
	DISTRIBUIDOR NUMBER(4, 0)
)
/
CREATE TABLE EAI.XSD_SCHEMAS
( 
	SCHEMANAME VARCHAR2(B, 40),
	ORDEN NUMBER(4, 0),
	NIVEL NUMBER(4, 0),
	TAGNAME VARCHAR2(B, 40),
	TAGDESCRIPTION VARCHAR2(B, 100),
	MAXOCCURS NUMBER(4, 0),
	MINOCCURS NUMBER(4, 0),
	TAGVALUETYPE VARCHAR2(B, 20),
	COMMENTS VARCHAR2(B, 50)
)
/
CREATE TABLE EAI.Z_CAMBIO_MES
( 
	FACTURA VARCHAR2(B, 20),
	FECHA_FACTURA DATE,
	FECHA DATE
)
/
CREATE TABLE EAI.Z_EMAIL
( 
	CLIENTE_SAP VARCHAR2(C, 30),
	RFC VARCHAR2(C, 30),
	NOMBRE VARCHAR2(C, 1024),
	SUCURSAL VARCHAR2(B, 40),
	EMAIL_ADDRESS VARCHAR2(B, 4000)
)
/
CREATE TABLE EAI.Z_MANTIS_AR
( 
	SUBTASK_ID VARCHAR2(B, 30),
	CREATED VARCHAR2(B, 30),
	CREATED_BY VARCHAR2(B, 30),
	OPENED_BY VARCHAR2(B, 50),
	SEVERITY VARCHAR2(B, 30),
	STATE VARCHAR2(B, 30),
	SHORT_DESCRIPTION VARCHAR2(B, 300),
	ASSIGNMENT_GROUP VARCHAR2(B, 60),
	CLOSED VARCHAR2(B, 30),
	CLASIFICACION_OBELIT VARCHAR2(B, 80)
)
/
CREATE TABLE EAI.Z_MANTIS_DATE_REF
( 
	REFERENCIA DATE,
	VALOR_REF NUMBER(14, 0)
)
/
CREATE TABLE EAI.Z_MANTIS_REQUEST
( 
	REQUEST VARCHAR2(B, 30),
	ID_NUMBER VARCHAR2(B, 30),
	CREATED VARCHAR2(B, 30),
	DUE_DATE VARCHAR2(B, 30),
	CREATED_BY VARCHAR2(B, 30),
	OPENED_BY VARCHAR2(B, 60),
	DESCRIPTION VARCHAR2(B, 300),
	SEVERITY VARCHAR2(B, 30),
	SHORT_DESCRIPTION VARCHAR2(B, 300),
	TASK_TYPE VARCHAR2(B, 30),
	ASSIGNMENT_GROUP VARCHAR2(B, 60),
	ASSIGNED_TO VARCHAR2(B, 60),
	CLOSED_BY VARCHAR2(B, 60),
	STATE VARCHAR2(B, 30),
	MADE_SLA VARCHAR2(B, 30),
	REQUESTED_FOR VARCHAR2(B, 30),
	SLA_DUE VARCHAR2(B, 30),
	APPROVAL VARCHAR2(B, 60),
	APPROVAL_SET VARCHAR2(B, 30),
	ACTIVE VARCHAR2(B, 30),
	CLOSED VARCHAR2(B, 30),
	ESCALATION VARCHAR2(B, 30),
	IMPACT VARCHAR2(B, 30),
	OPENED VARCHAR2(B, 30),
	URGENCY VARCHAR2(B, 30),
	STAGE VARCHAR2(B, 30),
	ITEM VARCHAR2(B, 80)
)
/
CREATE TABLE EAI.Z_SNOW_FOLLOW_UP
( 
	TASK_TYPE VARCHAR2(B, 60),
	TASK_ID VARCHAR2(B, 60),
	SUBTASK_ID VARCHAR2(B, 60),
	CREATED VARCHAR2(B, 60),
	DUE_DATE VARCHAR2(B, 60),
	CREATED_BY VARCHAR2(B, 60),
	OPENED_BY VARCHAR2(B, 60),
	SEVERITY VARCHAR2(B, 60),
	IMPACT VARCHAR2(B, 60),
	STATE VARCHAR2(B, 60),
	SHORT_DESCRIPTION VARCHAR2(B, 200),
	ASSIGNMENT_GROUP VARCHAR2(B, 60),
	RESOLVED_BY VARCHAR2(B, 60),
	RESOLVED VARCHAR2(B, 60),
	CLOSED VARCHAR2(B, 60),
	CLOSED_BY VARCHAR2(B, 60),
	DESCRIPTION VARCHAR2(B, 200),
	WORK_NOTES VARCHAR2(B, 60),
	RESOLVE_TIME VARCHAR2(B, 60),
	TASK_TYPE_2 VARCHAR2(B, 60),
	CLASIFICACION_OBELIT VARCHAR2(B, 60)
)
/
CREATE TABLE EAI.Z_TABLA_DWHDB
( 
	ORG_LV3_NAME VARCHAR2(B, 50),
	INVOICE_STATUS_LOC_NAME VARCHAR2(B, 50),
	INVOICE_TYPE_LOC_NAME VARCHAR2(B, 50),
	INVOICE_SUB_TYPE_LOC_NAME VARCHAR2(B, 50),
	AREA_NAME VARCHAR2(B, 50),
	TERRITORY_NAME VARCHAR2(B, 75),
	CUSTOMER_NUMBER VARCHAR2(B, 50),
	DUMMY_1 NUMBER,
	INVOICE_NUMBER VARCHAR2(B, 50),
	DOC_NUM VARCHAR2(B, 125),
	DUMMY_2 VARCHAR2(B, 50),
	CUSTOM_FIELD_14 VARCHAR2(B, 100),
	CUSTOMER_NAME VARCHAR2(B, 100),
	CUSTOMER_NAME_2 VARCHAR2(B, 100),
	PRICE_LIST_NAME VARCHAR2(B, 50),
	DUMMY_3 VARCHAR2(B, 3),
	CREDIT_LIMIT NUMBER(22, 7),
	CREDIT_DAYS NUMBER,
	DUMMY_4 NUMBER,
	DUMMY_5 VARCHAR2(B, 9),
	DUMMY_6 VARCHAR2(B, 23),
	OU_NUM VARCHAR2(B, 30),
	DUMMY_7 NUMBER,
	SKU_NAME VARCHAR2(B, 100),
	ITEM_CODE VARCHAR2(B, 50),
	PRODUCT_NAME VARCHAR2(B, 100),
	PRODUCT_VARIANT_NAME VARCHAR2(B, 100),
	PRODUCT_FAMILY_NAME VARCHAR2(B, 100),
	DWH_MONTH_ID NUMBER,
	DWH_WEEK_ID NUMBER,
	DWH_INVOICE_RAISED_DATE_ID NUMBER(38, 0)
)
/
CREATE TABLE EAI.Z_TABLA_SF_WA
( 
	FACTURA VARCHAR2(B, 50),
	ENTREGA_SF VARCHAR2(B, 50),
	ENTREGA_T3 VARCHAR2(B, 20),
	FECHFACTURASF VARCHAR2(B, 50),
	FECHFACTURAT3 VARCHAR2(B, 50),
	CLIENTE_SAP_1 VARCHAR2(B, 50),
	CLIENTE_SAP_2 VARCHAR2(B, 50),
	IMPORTE_SF NUMBER,
	IMPORTE_SAP NUMBER,
	IMPORTE_T3 NUMBER,
	IMPORTE_PROC NUMBER
)
/
CREATE TABLE EAI.ZMX_PAGOCENTRAL
( 
	CLIENTE_V3 VARCHAR2(C, 50),
	CLIENTE_SAP VARCHAR2(C, 30),
	RFC VARCHAR2(C, 30),
	NOMBRE VARCHAR2(C, 100),
	CADENA VARCHAR2(B, 20),
	DIST_COBZA VARCHAR2(B, 3),
	DIST_VENTA VARCHAR2(B, 20)
)
/
CREATE TABLE EAI.ZMX_STOCK_PARTNER
( 
	CLIENTE_SAP VARCHAR2(C, 30),
	SPECIALSTOCKPARTNER VARCHAR2(B, 40)
)
/
CREATE TABLE EAI.ZROBOT_PRINTED
( 
	REGION VARCHAR2(B, 30),
	SECTOR VARCHAR2(B, 30),
	TERRITORIO VARCHAR2(B, 30),
	CLIENTE_SAP VARCHAR2(B, 30),
	NOMBRE VARCHAR2(B, 99),
	ENTREGA_COBRO VARCHAR2(B, 30),
	LOCAL_FORANEO VARCHAR2(B, 30)
)
/
CREATE TABLE EAI.ZSDFE_APROB
( 
	SERIE VARCHAR2(B, 4),
	ANIO_APROB VARCHAR2(B, 10),
	NUM_APROB VARCHAR2(B, 10),
	LONGITUD NUMBER(2, 0),
	TIPO_DOCTO VARCHAR2(B, 20)
)
/
CREATE TABLE EAI.ZSDFE_SOC
( 
	BUKRS VARCHAR2(B, 4),
	KUNNR VARCHAR2(B, 10),
	RFC VARCHAR2(B, 15),
	RAZON_SOCIAL VARCHAR2(B, 60),
	CALLE VARCHAR2(B, 40),
	NUMERO_EXT VARCHAR2(B, 10),
	NUMERO_INT VARCHAR2(B, 10),
	COLONIA VARCHAR2(B, 40),
	LOCALIDAD VARCHAR2(B, 40),
	REFERENCIA VARCHAR2(B, 40),
	MUNICIPIO VARCHAR2(B, 40),
	ESTADO VARCHAR2(B, 40),
	PAIS VARCHAR2(B, 40),
	CODIGO_POSTAL NUMBER(5, 0),
	ANIO_APROB VARCHAR2(B, 10),
	NUM_APROB VARCHAR2(B, 10),
	RAZON_SOCIAL_HH VARCHAR2(B, 60)
)
/
ALTER TABLE EAI.AT_DISTRIB ADD CONSTRAINT PK_AT_DISTRIB
	PRIMARY KEY (DISTRIB)
/
ALTER TABLE EAI.AT_REP ADD CONSTRAINT PK_AT_REP
	PRIMARY KEY (LOGIN)
/
ALTER TABLE EAI.CAT_CREDIT_DAYS ADD CONSTRAINT PK_CAT_CREDIT_DAYS
	PRIMARY KEY (DAYS)
/
ALTER TABLE EAI.CUSTOMERS_T3_ERROR_LOG ADD CONSTRAINT PK_CUSTOMERS_T3_ERROR_LOG
	PRIMARY KEY (CUST_ID, LOG_DATE)
/
ALTER TABLE EAI.EAI_CUSTOMER_NO ADD CONSTRAINT PK_CUSTOMER_NO
	PRIMARY KEY (CUSTTYPE)
/
ALTER TABLE EAI.ENCUESTAS_CLIENTES_BITACORA ADD CONSTRAINT ENCUESTAS_CLIENTES_BITACO_PK
	PRIMARY KEY (IDEJECUCION)
/
ALTER TABLE EAI.ENCUESTAS_CLIENTES_ERRORES ADD CONSTRAINT ENCUESTAS_CLIENTES_ERRORE_PK
	PRIMARY KEY (IDERROR)
/
ALTER TABLE EAI.ENCUESTAS_CLIENTES_INVALIDAS ADD CONSTRAINT ENCUESTAS_CLIENTES_INVALI_PK
	PRIMARY KEY (IDENCUESTA_INVALIDA)
/
ALTER TABLE EAI.ENCUESTAS_CLIENTES_VALIDAS ADD CONSTRAINT ENCUESTAS_CLIENTES_VALIDA_PK
	PRIMARY KEY (IDENCUESTA)
/
ALTER TABLE EAI.FC__REP_DISTRIBUTOR ADD CONSTRAINT PK_FC__REP_DISTRIBUTOR
	PRIMARY KEY (CREATED)
/
ALTER TABLE EAI.IFC_FOLIOS_FE ADD CONSTRAINT IFC_FOLIOS_FE_PK
	PRIMARY KEY (ROW_ID)
/
ALTER TABLE EAI.OUT_CTRL ADD CONSTRAINT OUTCTL_PK
	PRIMARY KEY (DISTRIBUIDOR, STAGE)
/
ALTER TABLE EAI.PAYMENT_ERROR_LOG ADD CONSTRAINT SYS_C0016038
	CHECK ("ERROR" IS NOT NULL)
/
ALTER TABLE EAI.SDC_CADENA ADD CONSTRAINT PK_SDC_CADENA
	PRIMARY KEY (CADENA)
/
ALTER TABLE EAI.SDC_CARGA ADD CONSTRAINT PK_SDC_CARGA
	PRIMARY KEY (CADENA, CEDIS, PLAZA, TIENDA, ANIO, SEMANA, UPC)
/
ALTER TABLE EAI.SDC_CARGA_DIA ADD CONSTRAINT PK_SDC_CARGA_DIA
	PRIMARY KEY (CADENA, CEDIS, PLAZA, TIENDA, FECHA, UPC)
/
ALTER TABLE EAI.SDC_CEDIS ADD CONSTRAINT PK_SDC_CEDIS
	PRIMARY KEY (CADENA, CEDIS)
/
ALTER TABLE EAI.SDC_DISTRIBUCION_VENTA ADD CONSTRAINT PK_SDC_DISTIBUCION_VENTA
	PRIMARY KEY (CADENA, CEDIS, PLAZA, TIENDA, ANIO, SEMANA, MATERIAL)
/
ALTER TABLE EAI.SDC_ERROR ADD CONSTRAINT PK_SDC_ERROR
	PRIMARY KEY (CADENA, TIENDA, ANIO, SEMANA, NO_ERROR)
/
ALTER TABLE EAI.SDC_ERROR_DIARIA ADD CONSTRAINT PK_SDC_ERROR_DIARIA
	PRIMARY KEY (CADENA, TIENDA, FECHA, NO_ERROR)
/
ALTER TABLE EAI.SDC_ERROR_PUNTO_VENTA ADD CONSTRAINT SDC_ERROR_PUNTO_VENTA
	PRIMARY KEY (CADENA, PLAZA, ERROR, ANIOSEM, TIENDA, UPC)
/
ALTER TABLE EAI.SDC_ERROR_VENTA ADD CONSTRAINT PK_SDC_ERROR_VENTA
	PRIMARY KEY (CADENA, ANIOMES, PLAZA, ERROR)
/
ALTER TABLE EAI.SDC_HISTORIA ADD CONSTRAINT PK_SDC_HISTORIA
	PRIMARY KEY (CADENA, CEDIS, PLAZA, TIENDA, ANIO, MES, MATERIAL)
/
ALTER TABLE EAI.SDC_OXXO_DUNHILL_DIARIO ADD CONSTRAINT SDC_OXXO_DUNHILL_DIARIO_PK
	PRIMARY KEY (SEMANA_ID, UPC_CVE, NEGOCIO_DES)
/
ALTER TABLE EAI.SDC_PLAZA ADD CONSTRAINT PK_SDC_PLAZA
	PRIMARY KEY (CADENA, CEDIS, PLAZA)
/
ALTER TABLE EAI.SDC_PROCESO ADD CONSTRAINT PK_SDC_PROCESO
	PRIMARY KEY (ID_PROCESO)
/
ALTER TABLE EAI.SDC_TIENDA ADD CONSTRAINT PK_SDC_TIENDA
	PRIMARY KEY (CADENA, CEDIS, PLAZA, TIENDA)
/
ALTER TABLE EAI.SDC_VENTA_MEN_PDV ADD CONSTRAINT PK_SDC_VENTA_PDV
	UNIQUE (CADENA, CEDIS, ANIOMES, PLAZA_CVE, TIENDA_CVE, SKU)
/
ALTER TABLE EAI.SEVEN_PROCESO ADD CONSTRAINT SEVEN_PROCESO_PK
	PRIMARY KEY (ID_PROCESO)
/
ALTER TABLE EAI.ENCUESTAS_CLIENTES_ERRORES ADD CONSTRAINT ENCUESTAS_CLIENTES_ERRORE_FK1
	FOREIGN KEY (IDENCUESTA_INVALIDA)
		REFERENCES EAI.ENCUESTAS_CLIENTES_INVALIDAS (IDENCUESTA_INVALIDA)
/
ALTER TABLE EAI.SDC_CEDIS ADD CONSTRAINT FK_SDC_CEDIS
	FOREIGN KEY (CADENA)
		REFERENCES EAI.SDC_CADENA (CADENA)ON DELETE CASCADE
/
ALTER TABLE EAI.SDC_DISTRIBUCION_VENTA ADD CONSTRAINT FK_SDC_DISTRIBUCION_VENTA
	FOREIGN KEY (CADENA, CEDIS, PLAZA, TIENDA)
		REFERENCES EAI.SDC_TIENDA (CADENA, CEDIS, PLAZA, TIENDA)
/
ALTER TABLE EAI.SDC_PLAZA ADD CONSTRAINT FK_SDC_PLAZA
	FOREIGN KEY (CADENA, CEDIS)
		REFERENCES EAI.SDC_CEDIS (CADENA, CEDIS)ON DELETE CASCADE
/
ALTER TABLE EAI.SDC_TIENDA ADD CONSTRAINT FK_SDC_TIENDA
	FOREIGN KEY (CADENA, CEDIS, PLAZA)
		REFERENCES EAI.SDC_PLAZA (CADENA, CEDIS, PLAZA)ON DELETE CASCADE
/
CREATE INDEX EAI.CFDI_BITACORA_DOC_NUM_IX ON EAI.CFDI_BITACORA
(
	DOC_NUM
)
/
CREATE INDEX EAI.CFDI_OPEN_ITEMS_IX ON EAI.CFDI_OPEN_ITEMS
(
	NOTA_VENTA
)
/
CREATE INDEX EAI.CLIENTES_SIEBEL_I1 ON EAI.CLIENTE_SIEBEL
(
	CLIENTE_V3,
	CLIENTE_SAP
)
/
CREATE INDEX EAI.CLIENTES_SIEBEL_I2 ON EAI.CLIENTE_SIEBEL
(
	CLIENTE_V3,
	DIAS_CDTO,
	RFC,
	LISTA_IVA,
	LISTA_PRECIO,
	TERRITORIO,
	DIST_COBZA,
	FORMA_PAGO
)
/
CREATE INDEX EAI.CUSTOMER_LOG_IX ON EAI.CUSTOMER_LOG
(
	CLIENTE_V3,
	FECHA_INSERT
)
/
CREATE INDEX EAI.ENCUESTAS_BITACORA_INDEX1 ON EAI.ENCUESTAS_CLIENTES_BITACORA
(
	FECHA_HORA
)
/
CREATE INDEX EAI.ENCUESTAS_CARGADAS_INDEX1 ON EAI.ENCUESTAS_CLIENTES_CARGADAS
(
	IDENCUESTADO
)
/
CREATE INDEX EAI.ENCUESTAS_CARGADAS_INDEX2 ON EAI.ENCUESTAS_CLIENTES_CARGADAS
(
	IDENCUESTADOR
)
/
CREATE INDEX EAI.ENCUESTAS_CARGADAS_INDEX3 ON EAI.ENCUESTAS_CLIENTES_CARGADAS
(
	TERRITORIO
)
/
CREATE INDEX EAI.ENCUESTAS_CARGADAS_INDEX4 ON EAI.ENCUESTAS_CLIENTES_CARGADAS
(
	DIA_VISITA
)
/
CREATE INDEX EAI.ENCUESTAS_CARGADAS_INDEX5 ON EAI.ENCUESTAS_CLIENTES_CARGADAS
(
	CONSECUTIVO
)
/
CREATE INDEX EAI.ENCUESTAS_CARGADAS_INDEX6 ON EAI.ENCUESTAS_CLIENTES_CARGADAS
(
	SEMANA
)
/
CREATE INDEX EAI.ENCUESTAS_ERRORES_INDEX1 ON EAI.ENCUESTAS_CLIENTES_ERRORES
(
	IDENCUESTA_INVALIDA
)
/
CREATE INDEX EAI.ENCUESTAS_ERRORES_INDEX2 ON EAI.ENCUESTAS_CLIENTES_ERRORES
(
	FECHA_REGISTRO
)
/
CREATE INDEX EAI.ENCUESTAS_ERRORES_INDEX3 ON EAI.ENCUESTAS_CLIENTES_ERRORES
(
	CAMPO_ERROR
)
/
CREATE INDEX EAI.ENCUESTAS_INEGI_INDEX1 ON EAI.ENCUESTAS_CLIENTES_INEGI
(
	TERRITORIO
)
/
CREATE INDEX EAI.ENCUESTAS_INEGI_INDEX2 ON EAI.ENCUESTAS_CLIENTES_INEGI
(
	SEMANA
)
/
CREATE INDEX EAI.ENCUESTAS_INEGI_INDEX3 ON EAI.ENCUESTAS_CLIENTES_INEGI
(
	DIA_DE_VISITA
)
/
CREATE INDEX EAI.ENCUESTAS_INEGI_INDEX4 ON EAI.ENCUESTAS_CLIENTES_INEGI
(
	CONSECUTIVO
)
/
CREATE INDEX EAI.ENCUESTAS_INEGI_INDEX5 ON EAI.ENCUESTAS_CLIENTES_INEGI
(
	CLAVE
)
/
CREATE INDEX EAI.ENCUESTAS_INEGI_INDEX6 ON EAI.ENCUESTAS_CLIENTES_INEGI
(
	ID
)
/
CREATE INDEX EAI.ENCUESTAS_INEGI_INDEX7 ON EAI.ENCUESTAS_CLIENTES_INEGI
(
	ID_BAT
)
/
CREATE INDEX EAI.ENCUESTAS_INVALIDAS_INDEX1 ON EAI.ENCUESTAS_CLIENTES_INVALIDAS
(
	TERRITORIO,
	ANIO_SEMANA,
	DIA_SEMANA,
	CONSECUTIVO
)
/
CREATE INDEX EAI.ENCUESTAS_INVALIDAS_INDEX2 ON EAI.ENCUESTAS_CLIENTES_INVALIDAS
(
	IDEJECUCION
)
/
CREATE INDEX EAI.ENCUESTAS_INVALIDAS_INDEX3 ON EAI.ENCUESTAS_CLIENTES_INVALIDAS
(
	TERRITORIO
)
/
CREATE INDEX EAI.ENCUESTAS_INVALIDAS_INDEX4 ON EAI.ENCUESTAS_CLIENTES_INVALIDAS
(
	ANIO_SEMANA
)
/
CREATE INDEX EAI.ENCUESTAS_INVALIDAS_INDEX5 ON EAI.ENCUESTAS_CLIENTES_INVALIDAS
(
	DIA_SEMANA
)
/
CREATE INDEX EAI.ENCUESTAS_INVALIDAS_INDEX6 ON EAI.ENCUESTAS_CLIENTES_INVALIDAS
(
	CONSECUTIVO
)
/
CREATE INDEX EAI.ENCUESTAS_INVALIDAS_INDEX7 ON EAI.ENCUESTAS_CLIENTES_INVALIDAS
(
	IDENCUESTADO
)
/
CREATE INDEX EAI.ENCUESTAS_INVALIDAS_INDEX8 ON EAI.ENCUESTAS_CLIENTES_INVALIDAS
(
	IDENCUESTADOR
)
/
CREATE INDEX EAI.ENCUESTAS_INVALIDAS_INDEX9 ON EAI.ENCUESTAS_CLIENTES_INVALIDAS
(
	FECHA_INICIO
)
/
CREATE INDEX EAI.ENCUESTAS_RESUMEN_INDEX1 ON EAI.ENCUESTAS_CLIENTES_RESUMEN
(
	IDENCUESTADO
)
/
CREATE INDEX EAI.ENCUESTAS_RESUMEN_INDEX2 ON EAI.ENCUESTAS_CLIENTES_RESUMEN
(
	IDENCUESTADOR
)
/
CREATE INDEX EAI.ENCUESTAS_RESUMEN_INDEX3 ON EAI.ENCUESTAS_CLIENTES_RESUMEN
(
	TERRITORIO
)
/
CREATE INDEX EAI.ENCUESTAS_RESUMEN_INDEX4 ON EAI.ENCUESTAS_CLIENTES_RESUMEN
(
	DIA_VISITA
)
/
CREATE INDEX EAI.ENCUESTAS_RESUMEN_INDEX5 ON EAI.ENCUESTAS_CLIENTES_RESUMEN
(
	CONSECUTIVO
)
/
CREATE INDEX EAI.ENCUESTAS_RESUMEN_INDEX6 ON EAI.ENCUESTAS_CLIENTES_RESUMEN
(
	SEMANA
)
/
CREATE INDEX EAI.ENCUESTAS_VALIDAS_INDEX1 ON EAI.ENCUESTAS_CLIENTES_VALIDAS
(
	TERRITORIO
)
/
CREATE INDEX EAI.ENCUESTAS_VALIDAS_INDEX2 ON EAI.ENCUESTAS_CLIENTES_VALIDAS
(
	ANIO_SEMANA
)
/
CREATE INDEX EAI.ENCUESTAS_VALIDAS_INDEX3 ON EAI.ENCUESTAS_CLIENTES_VALIDAS
(
	DIA_SEMANA
)
/
CREATE INDEX EAI.ENCUESTAS_VALIDAS_INDEX5 ON EAI.ENCUESTAS_CLIENTES_VALIDAS
(
	IDENCUESTADO
)
/
CREATE INDEX EAI.ENCUESTAS_VALIDAS_INDEX6 ON EAI.ENCUESTAS_CLIENTES_VALIDAS
(
	IDENCUESTADOR
)
/
CREATE INDEX EAI.ENCUESTAS_VALIDAS_INDEX7 ON EAI.ENCUESTAS_CLIENTES_VALIDAS
(
	SEMANA
)
/
CREATE INDEX EAI.ENCUESTAS_VALIDAS_INDEX8 ON EAI.ENCUESTAS_CLIENTES_VALIDAS
(
	FECHA_INICIO
)
/
CREATE INDEX EAI.ENCUESTAS_VALIDAS_INDEX9 ON EAI.ENCUESTAS_CLIENTES_VALIDAS
(
	TERRITORIO,
	ANIO_SEMANA,
	DIA_SEMANA,
	CONSECUTIVO
)
/
CREATE INDEX EAI.I1_FC__REP_DISTRIBUTOR ON EAI.FC__REP_DISTRIBUTOR
(
	REP_ID,
	START_DATE,
	END_DATE
)
/
CREATE UNIQUE INDEX EAI.IDX_CONTROL_REPORTE ON EAI.CONTROL_REPORTE
(
	REPORTE
)
/
CREATE INDEX EAI.IFC_FOLIOS_CONFIG_EMAIL_INDEX1 ON EAI.IFC_FOLIOS_CONFIG_EMAIL
(
	RFC,
	CLIENTE_V3
)
/
CREATE INDEX EAI.IFC_FOLIOS_FE_CREADOPOR ON EAI.IFC_FOLIOS_FE
(
	CREADOPOR,
	ROW_ID
)
/
CREATE INDEX EAI.IFC_FOLIOS_FE_DOCNUM ON EAI.IFC_FOLIOS_FE
(
	VAR_1
)
/
CREATE INDEX EAI.IX_DELPHIC_SEMANA_CLIENTE ON EAI.LDR_DELPHIC
(
	WEEK_START,
	SAP_CUSTOMER_CLEAN,
	SKU_CODE
)
/
CREATE INDEX EAI.SDC_CARGA_DIA_LDR_INDEX1 ON EAI.SDC_CARGA_DIA_LDR
(
	TIEMPO_ID
)
/
CREATE INDEX EAI.SDC_OXXO_DUNHILL_DIARIO_INDEX1 ON EAI.SDC_OXXO_DUNHILL_DIARIO
(
	SEMANA_ID,
	NEGOCIO_DES
)
/
CREATE UNIQUE INDEX EAI.SDC_VENTA_IDX1 ON EAI.SDC_VENTA
(
	CADENA,
	ANIOMES,
	PLAZA,
	SKU
)
/
CREATE INDEX EAI.T3R_CARTERA_SAP_OLD_FACT_IX ON EAI.T3R_CARTERA_SAP_OLD
(
	ASIGNACION
)
/
CREATE INDEX EAI.T3R_SALES_DOCS_FACTURA ON EAI.T3R_SALES_DOCS_OLD
(
	DOC_NUM_REF2
)
/
CREATE INDEX EAI.T3R_SALES_DOCS_ORDER_NUM ON EAI.T3R_SALES_DOCS_OLD
(
	DOC_NUM_REF1
)
/
CREATE INDEX EAI.T3R_SALES_DOCS_OTHERS_PK ON EAI.T3R_SALES_DOCS_OTHERS
(
	DOC_NUM_R3
)
/
