--------------------------------------------------------
--  File created - Thursday-June-18-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACTUAL_STOCK
--------------------------------------------------------

  CREATE TABLE "EAI_OWNER"."ACTUAL_STOCK" 
   (	"ID" VARCHAR2(1024 BYTE), 
	"VAN" VARCHAR2(1024 BYTE), 
	"VAN_ID" VARCHAR2(1024 BYTE), 
	"TIPO_VAN" VARCHAR2(1024 BYTE), 
	"OWNER" VARCHAR2(1024 BYTE), 
	"RESOURCE_ID" VARCHAR2(1024 BYTE), 
	"MANUF_SKU_ERPNUMBER" VARCHAR2(1024 BYTE), 
	"MANUF_SKU_ERPNUM_CORTO" VARCHAR2(1024 BYTE), 
	"UOM1_QTY" NUMBER, 
	"AVAILABLE_QTY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LEGDB_INDX01" ;
  GRANT SELECT ON "EAI_OWNER"."ACTUAL_STOCK" TO "ITX_DEV";
  GRANT ALTER ON "EAI_OWNER"."ACTUAL_STOCK" TO "SYSADMIN_ROLE";
  GRANT DELETE ON "EAI_OWNER"."ACTUAL_STOCK" TO "SYSADMIN_ROLE";
  GRANT INSERT ON "EAI_OWNER"."ACTUAL_STOCK" TO "SYSADMIN_ROLE";
  GRANT SELECT ON "EAI_OWNER"."ACTUAL_STOCK" TO "SYSADMIN_ROLE";
  GRANT UPDATE ON "EAI_OWNER"."ACTUAL_STOCK" TO "SYSADMIN_ROLE";
  GRANT ON COMMIT REFRESH ON "EAI_OWNER"."ACTUAL_STOCK" TO "SYSADMIN_ROLE";
  GRANT QUERY REWRITE ON "EAI_OWNER"."ACTUAL_STOCK" TO "SYSADMIN_ROLE";
  GRANT DEBUG ON "EAI_OWNER"."ACTUAL_STOCK" TO "SYSADMIN_ROLE";
  GRANT FLASHBACK ON "EAI_OWNER"."ACTUAL_STOCK" TO "SYSADMIN_ROLE";
