--------------------------------------------------------
--  File created - Thursday-June-18-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CAT_OFICIAL_COLONIA
--------------------------------------------------------

  CREATE TABLE "EAI_OWNER"."CAT_OFICIAL_COLONIA" 
   (	"C_MUNICIPIO" VARCHAR2(6 BYTE), 
	"C_COLONIA" VARCHAR2(4 BYTE), 
	"C_CODIGOPOSTAL" VARCHAR2(5 BYTE), 
	"C_NOMBREASENTAMIENTO" VARCHAR2(120 BYTE), 
	"C_CODIGOPOSTAL_SAT" VARCHAR2(5 BYTE), 
	"C_ASENTAMIENTO_SAT" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LEGDB_INDX01" ;
  GRANT ALTER ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "T3";
  GRANT DELETE ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "T3";
  GRANT INDEX ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "T3";
  GRANT INSERT ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "T3";
  GRANT SELECT ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "T3";
  GRANT UPDATE ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "T3";
  GRANT REFERENCES ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "T3";
  GRANT READ ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "T3";
  GRANT ON COMMIT REFRESH ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "T3";
  GRANT QUERY REWRITE ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "T3";
  GRANT DEBUG ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "T3";
  GRANT FLASHBACK ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "T3";
  GRANT ALTER ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "SYSADMIN_ROLE";
  GRANT DELETE ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "SYSADMIN_ROLE";
  GRANT INSERT ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "SYSADMIN_ROLE";
  GRANT SELECT ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "SYSADMIN_ROLE";
  GRANT UPDATE ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "SYSADMIN_ROLE";
  GRANT READ ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "SYSADMIN_ROLE";
  GRANT ON COMMIT REFRESH ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "SYSADMIN_ROLE";
  GRANT QUERY REWRITE ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "SYSADMIN_ROLE";
  GRANT DEBUG ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "SYSADMIN_ROLE";
  GRANT FLASHBACK ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "SYSADMIN_ROLE";
  GRANT ALTER ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "INTEGRATION_ROLE";
  GRANT DELETE ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "INTEGRATION_ROLE";
  GRANT INSERT ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "INTEGRATION_ROLE";
  GRANT SELECT ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "INTEGRATION_ROLE";
  GRANT UPDATE ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "INTEGRATION_ROLE";
  GRANT READ ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "INTEGRATION_ROLE";
  GRANT ON COMMIT REFRESH ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "INTEGRATION_ROLE";
  GRANT QUERY REWRITE ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "INTEGRATION_ROLE";
  GRANT DEBUG ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "INTEGRATION_ROLE";
  GRANT FLASHBACK ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "INTEGRATION_ROLE";
  GRANT SELECT ON "EAI_OWNER"."CAT_OFICIAL_COLONIA" TO "ITX_DEV";
