--------------------------------------------------------
--  File created - Thursday-June-18-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATALOGO_COLONIA_SAT
--------------------------------------------------------

  CREATE TABLE "EAI_OWNER"."CATALOGO_COLONIA_SAT" 
   (	"C_COLONIA" VARCHAR2(20 BYTE), 
	"C_CODIGOPOSTAL" VARCHAR2(20 BYTE), 
	"NOMBRE_ASENTAMIENTO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LEGDB_INDX01" ;
  GRANT SELECT ON "EAI_OWNER"."CATALOGO_COLONIA_SAT" TO "ITX_DEV";
